// AUTOGENERATED CODE on 2026-05-25T02:03:42.254583 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(biosao_bio_code, BM_BIOSAO_BIO_START, BM_BIOSAO_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "li	a0, 0",
    "lui	a1, 262144",
    // --- inline asm begin ---
    "mv	x26, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "addi	a2, a1, -1",
    "lui	a3, 122",
    "addi	a3, a3, 288",
    "22:", // .LBB1_1: =>This Loop Header: Depth=1
    // Child Loop BB1_2 Depth 2
    // Child Loop BB1_7 Depth 2
    // --- inline asm begin ---
    "mv	a4, x31",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    "23:", // .LBB1_2: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a5, x21",
    // --- inline asm end ---
    "beqz	a5, 23b",
    // in Loop: Header=BB1_1 Depth=1
    "and	a4, a4, a2",
    // --- inline asm begin ---
    "mv	a5, x31",
    // --- inline asm end ---
    "and	a5, a5, a2",
    "bltu	a4, a5, 24f",
    // in Loop: Header=BB1_1 Depth=1
    "xor	a5, a5, a2",
    "add	a4, a4, a5",
    "j	25f",
    "24:", // .LBB1_5: in Loop: Header=BB1_1 Depth=1
    "sub	a4, a5, a4",
    "25:", // .LBB1_6: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x19, a4",
    // --- inline asm end ---
    "mv	a4, a3",
    "26:", // .LBB1_7: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a4, a4, -1",
    "bnez	a4, 26b",
    // in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x24, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "j	22b"
);
