// AUTOGENERATED CODE on 2026-05-25T13:49:10.494876 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(biosao_bio_code, BM_BIOSAO_BIO_START, BM_BIOSAO_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "li	a0, 0",
    "lui	a1, 262144",
    // --- inline asm begin ---
    "mv	x26, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "addi	a2, a1, -1",
    "22:", // .LBB1_1: =>This Loop Header: Depth=1
    // Child Loop BB1_2 Depth 2
    // --- inline asm begin ---
    "mv	a3, x31",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a1",
    // --- inline asm end ---
    "23:", // .LBB1_2: Parent Loop BB1_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a4, x21",
    // --- inline asm end ---
    "beqz	a4, 23b",
    // in Loop: Header=BB1_1 Depth=1
    "and	a3, a3, a2",
    // --- inline asm begin ---
    "mv	a4, x31",
    // --- inline asm end ---
    "and	a4, a4, a2",
    "bltu	a3, a4, 24f",
    // in Loop: Header=BB1_1 Depth=1
    "xor	a4, a4, a2",
    "add	a3, a3, a4",
    "j	25f",
    "24:", // .LBB1_5: in Loop: Header=BB1_1 Depth=1
    "sub	a3, a4, a3",
    "25:", // .LBB1_6: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "mv	x19, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a3, x19",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a0",
    // --- inline asm end ---
    "j	22b"
);
