// AUTOGENERATED CODE on 2026-04-03T23:15:10.743679 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(lightgenes_bio_code, BM_LIGHTGENES_BIO_START, BM_LIGHTGENES_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	75f",
    // --- inline asm end ---
    "21:", // fp_div: @fp_div
    "lui	a2, 524288",
    "beqz	a1, 26f",
    "srai	a3, a0, 31",
    "srai	a4, a1, 31",
    "xor	a5, a0, a3",
    "sub	t2, a5, a3",
    "xor	a5, a1, a4",
    "sub	a4, a5, a4",
    "lui	a5, 16",
    "bgeu	a4, t2, 23f",
    "22:", // .LBB1_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "slli	a5, a5, 1",
    "bltu	a4, t2, 22b",
    "beqz	a5, 26f",
    "23:", // .LBB1_4
    "srli	t0, a4, 31",
    "srl	t1, a4, t0",
    "li	a4, 0",
    "beqz	a0, 25f",
    "srl	a5, a5, t0",
    "li	t0, 2",
    "24:", // .LBB1_6: =>This Inner Loop Header: Depth=1
    "sltu	a2, t2, t1",
    "addi	a2, a2, -1",
    "and	a3, a2, t1",
    "and	a2, a2, a5",
    "sub	t2, t2, a3",
    "or	a4, a4, a2",
    "slli	t2, t2, 1",
    "bltu	a5, t0, 25f",
    // in Loop: Header=BB1_6 Depth=1
    "srli	a5, a5, 1",
    "bnez	t2, 24b",
    "25:", // .LBB1_8
    "sltu	a2, t2, t1",
    "xori	a2, a2, 1",
    "xor	a0, a0, a1",
    "add	a2, a2, a4",
    "bgez	a0, 26f",
    "neg	a2, a2",
    "26:", // .LBB1_10
    "mv	a0, a2",
    "ret",
    "27:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // __udivsi3: @__udivsi3
    "beqz	a1, 35f",
    "mv	t2, a0",
    "li	a4, 0",
    "li	a0, 0",
    "li	a3, 31",
    "li	t0, 1",
    "li	t1, -1",
    "34:", // .LBB3_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	a5, t2, a3",
    "sll	a2, t0, a3",
    "addi	a3, a3, -1",
    "andi	a5, a5, 1",
    "or	a4, a4, a5",
    "sltu	a5, a4, a1",
    "addi	a5, a5, -1",
    "and	a2, a2, a5",
    "and	a5, a5, a1",
    "or	a0, a0, a2",
    "sub	a4, a4, a5",
    "bne	a3, t1, 34b",
    "ret",
    "35:", // .LBB3_4
    "li	a0, -1",
    "ret",
    "36:", // __umodsi3: @__umodsi3
    "beqz	a1, 38f",
    "li	a2, 0",
    "li	a3, 31",
    "li	a4, -1",
    "37:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a0, a3",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a3, a3, -1",
    "sub	a2, a2, a5",
    "bne	a3, a4, 37b",
    "j	39f",
    "38:", // .LBB4_3
    "mv	a2, a0",
    "39:", // .LBB4_4
    "mv	a0, a2",
    "ret",
    "40:", // __divsi3: @__divsi3
    "addi	sp, sp, -16",
    "sw	s0, 12(sp)", // 4-byte Folded Spill
    "sw	s1, 8(sp)", // 4-byte Folded Spill
    "mv	t0, a0",
    "beqz	a1, 42f",
    "li	a4, 0",
    "li	a0, 0",
    "srai	t2, t0, 31",
    "srai	s0, a1, 31",
    "li	a3, 31",
    "li	t1, 1",
    "xor	a5, t0, t2",
    "sub	a5, a5, t2",
    "xor	a2, a1, s0",
    "sub	a2, a2, s0",
    "li	t2, -1",
    "41:", // .LBB5_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	s0, a5, a3",
    "sll	s1, t1, a3",
    "addi	a3, a3, -1",
    "andi	s0, s0, 1",
    "or	a4, a4, s0",
    "sltu	s0, a4, a2",
    "addi	s0, s0, -1",
    "and	s1, s1, s0",
    "and	s0, s0, a2",
    "or	a0, a0, s1",
    "sub	a4, a4, s0",
    "bne	a3, t2, 41b",
    "j	43f",
    "42:", // .LBB5_3
    "li	a0, -1",
    "43:", // .LBB5_4
    "xor	a1, a1, t0",
    "bgez	a1, 44f",
    "neg	a0, a0",
    "44:", // .LBB5_6
    "lw	s0, 12(sp)", // 4-byte Folded Reload
    "lw	s1, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "45:", // __modsi3: @__modsi3
    "srai	a2, a0, 31",
    "xor	a3, a0, a2",
    "sub	a3, a3, a2",
    "beqz	a1, 49f",
    "li	a2, 0",
    "srai	a5, a1, 31",
    "li	a4, 31",
    "xor	a1, a1, a5",
    "sub	a1, a1, a5",
    "li	t0, -1",
    "46:", // .LBB6_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a3, a4",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a4, a4, -1",
    "sub	a2, a2, a5",
    "bne	a4, t0, 46b",
    "bgez	a0, 48f",
    "47:", // .LBB6_4
    "neg	a2, a2",
    "48:", // .LBB6_5
    "mv	a0, a2",
    "ret",
    "49:", // .LBB6_6
    "mv	a2, a3",
    "bltz	a0, 47b",
    "j	48b",
    "50:", // HsvToRgb: @HsvToRgb
    "slli	a4, a0, 16",
    "srli	a4, a4, 24",
    "srli	a1, a0, 16",
    "beqz	a4, 51f",
    "andi	a2, a0, 255",
    "li	a3, 191",
    "li	t0, 213",
    "andi	a5, a1, 255",
    "mul	a3, a2, a3",
    "xori	a2, a4, 255",
    "mul	a2, a2, a5",
    "srli	a3, a3, 13",
    "srli	t1, a2, 8",
    "mul	a2, a3, t0",
    "add	a0, a0, a2",
    "slli	a2, a0, 1",
    "slli	a0, a0, 3",
    "sub	a0, a0, a2",
    "andi	a0, a0, 254",
    "mul	a2, a0, a4",
    "xori	a0, a0, 255",
    "srli	a2, a2, 8",
    "mul	a0, a0, a4",
    "xori	a2, a2, 255",
    "srli	a0, a0, 8",
    "mul	a2, a2, a5",
    "xori	a4, a0, 255",
    "srli	a0, a2, 8",
    "mul	a5, a4, a5",
    "li	a2, 1",
    "srli	a5, a5, 8",
    "bge	a2, a3, 52f",
    "li	a2, 2",
    "beq	a3, a2, 53f",
    "li	a2, 3",
    "beq	a3, a2, 54f",
    "li	a2, 4",
    "bne	a3, a2, 58f",
    "mv	a3, a5",
    "mv	a4, t1",
    "j	55f",
    "51:", // .LBB7_6
    "mv	a3, a1",
    "mv	a4, a1",
    "j	55f",
    "52:", // .LBB7_7
    "beqz	a3, 56f",
    "li	a2, 1",
    "bne	a3, a2, 58f",
    "mv	a3, a0",
    "mv	a4, a1",
    "j	57f",
    "53:", // .LBB7_10
    "mv	a3, t1",
    "mv	a4, a1",
    "mv	a0, a5",
    "j	59f",
    "54:", // .LBB7_11
    "mv	a3, t1",
    "mv	a4, a0",
    "55:", // .LBB7_12
    "mv	a0, a1",
    "j	59f",
    "56:", // .LBB7_13
    "mv	a3, a1",
    "mv	a4, a5",
    "57:", // .LBB7_14
    "mv	a0, t1",
    "j	59f",
    "58:", // .LBB7_15
    "mv	a3, a1",
    "mv	a4, t1",
    "59:", // .LBB7_16
    "slli	a0, a0, 24",
    "slli	a4, a4, 24",
    "srli	a0, a0, 8",
    "srli	a4, a4, 16",
    "andi	a1, a3, 255",
    "or	a1, a1, a4",
    "or	a0, a0, a1",
    "ret",
    "60:", // satsub_8: @satsub_8
    "sub	a1, a0, a1",
    "sltu	a0, a0, a1",
    "addi	a0, a0, -1",
    "and	a0, a0, a1",
    "ret",
    "61:", // satadd_8: @satadd_8
    "add	a0, a0, a1",
    "li	a1, 255",
    "bltu	a0, a1, 62f",
    "li	a0, 255",
    "62:", // .LBB9_2
    "ret",
    "63:", // satadd_8_limit: @satadd_8_limit
    "add	a0, a0, a1",
    "bltu	a0, a2, 64f",
    "mv	a0, a2",
    "64:", // .LBB10_2
    "ret",
    "65:", // satsub_8p: @satsub_8p
    "andi	a2, a0, 255",
    "slli	a3, a0, 16",
    "slli	a0, a0, 8",
    "srli	a3, a3, 24",
    "srli	a0, a0, 24",
    "sub	a4, a2, a1",
    "sltu	a2, a2, a4",
    "addi	a2, a2, -1",
    "and	a2, a2, a4",
    "sub	a4, a3, a1",
    "sub	a1, a0, a1",
    "sltu	a3, a3, a4",
    "sltu	a0, a0, a1",
    "addi	a3, a3, -1",
    "addi	a0, a0, -1",
    "and	a3, a3, a4",
    "and	a0, a0, a1",
    "slli	a0, a0, 16",
    "slli	a3, a3, 8",
    "or	a0, a0, a3",
    "or	a0, a0, a2",
    "ret",
    "66:", // satadd_8p: @satadd_8p
    "slli	a2, a0, 16",
    "srli	a2, a2, 24",
    "add	a2, a2, a1",
    "li	a3, 255",
    "bltu	a2, a3, 67f",
    "li	a2, 255",
    "67:", // .LBB12_2
    "andi	a4, a0, 255",
    "add	a4, a4, a1",
    "bltu	a4, a3, 68f",
    "li	a4, 255",
    "68:", // .LBB12_4
    "slli	a0, a0, 8",
    "srli	a0, a0, 24",
    "add	a1, a1, a0",
    "bltu	a1, a3, 69f",
    "li	a1, 255",
    "69:", // .LBB12_6
    "slli	a1, a1, 16",
    "slli	a2, a2, 8",
    "or	a0, a1, a2",
    "or	a0, a0, a4",
    "ret",
    "70:", // map_16: @map_16
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "mv	s0, a3",
    "mv	s1, a1",
    "sw	a0, 0(sp)", // 4-byte Folded Spill
    "sub	a0, a4, a3",
    "sub	a1, a2, a1",
    "slli	a0, a0, 16",
    "slli	a1, a1, 16",
    "jal	ra, 21b",
    "lw	a1, 0(sp)", // 4-byte Folded Reload
    "sub	a1, a1, s1",
    "slli	a1, a1, 16",
    "mulh	a0, a0, a1",
    "add	a0, a0, s0",
    "slli	a0, a0, 16",
    "srai	a0, a0, 16",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "lw	s1, 4(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "71:", // map: @map
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "mv	s0, a3",
    "sub	a0, a0, a1",
    "sub	a4, a4, a3",
    "mul	a0, a4, a0",
    "sub	a1, a2, a1",
    "jal	ra, 40b",
    "add	a0, a0, s0",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "72:", // test_pattern: @test_pattern
    "beqz	a0, 74f",
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "mv	s0, a0",
    "lui	a0, %hi(102f)",
    "lw	a1, %lo(102f)(a0)",
    "addi	s1, a0, %lo(102f)",
    "slli	a0, a1, 23",
    "srli	a0, a0, 24",
    "mv	a1, s0",
    "jal	ra, 36b",
    "addi	a1, s1, 24",
    "lui	a2, 16",
    "addi	a2, a2, 257",
    "73:", // .LBB15_2: =>This Inner Loop Header: Depth=1
    "snez	a3, a0",
    "addi	s0, s0, -1",
    "addi	a3, a3, -1",
    "and	a3, a3, a2",
    "sw	a3, 0(a1)",
    "addi	a1, a1, 4",
    "addi	a0, a0, -1",
    "bnez	s0, 73b",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "lw	s1, 4(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "74:", // .LBB15_4
    "ret",
    "75:", // main: @main
    "addi	sp, sp, -144",
    "sw	ra, 140(sp)", // 4-byte Folded Spill
    "sw	s0, 136(sp)", // 4-byte Folded Spill
    "sw	s1, 132(sp)", // 4-byte Folded Spill
    "li	a1, 0",
    "sw	zero, 28(sp)", // 4-byte Folded Spill
    "lui	a4, 101",
    // --- inline asm begin ---
    "mv	x27, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "sw	a0, 24(sp)", // 4-byte Folded Spill
    "lui	t1, 16",
    "lui	t2, 2",
    "lui	ra, 4112",
    "lui	t0, 838861",
    "lui	a5, 50",
    "lui	a2, 25",
    "lui	a3, 10",
    "lui	a0, 96",
    "lui	a1, 112",
    "addi	s1, a4, -1921",
    "addi	s0, t1, 257",
    "addi	a4, t2, -1522",
    "sw	a4, 120(sp)", // 4-byte Folded Spill
    "addi	a4, ra, 258",
    "sw	a4, 20(sp)", // 4-byte Folded Spill
    "addi	a4, t0, -819",
    "sw	a4, 16(sp)", // 4-byte Folded Spill
    "addi	a4, a5, 1087",
    "sw	a4, 112(sp)", // 4-byte Folded Spill
    "addi	a2, a2, 545",
    "sw	a2, 124(sp)", // 4-byte Folded Spill
    "addi	a2, a3, -1163",
    "sw	a2, 64(sp)", // 4-byte Folded Spill
    "addi	a0, a0, 1542",
    "sw	a0, 36(sp)", // 4-byte Folded Spill
    "addi	a0, a1, 1792",
    "sw	a0, 48(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	a2, x17",
    // --- inline asm end ---
    "lui	a1, 1048560",
    "slli	a0, a2, 16",
    "add	a0, a0, a1",
    "sw	a0, 60(sp)", // 4-byte Folded Spill
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "lui	a0, %hi(102f)",
    "addi	a1, a2, -2",
    "sw	a1, 100(sp)", // 4-byte Folded Spill
    "srli	a1, a2, 1",
    "sw	a1, 4(sp)", // 4-byte Folded Spill
    "addi	a1, a4, 24",
    "sw	a1, 8(sp)", // 4-byte Folded Spill
    "addi	a0, a0, %lo(102f)",
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    "li	a5, 57",
    "sw	s0, 0(sp)", // 4-byte Folded Spill
    "sw	a2, 44(sp)", // 4-byte Folded Spill
    "sw	s1, 116(sp)", // 4-byte Folded Spill
    "76:", // .LBB16_1: =>This Loop Header: Depth=1
    // Child Loop BB16_4 Depth 2
    // Child Loop BB16_12 Depth 2
    // Child Loop BB16_21 Depth 3
    // Child Loop BB16_42 Depth 2
    // Child Loop BB16_37 Depth 2
    // Child Loop BB16_38 Depth 3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 77f",
    // in Loop: Header=BB16_1 Depth=1
    "lw	a0, 24(sp)", // 4-byte Folded Reload
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "mv	s0, a2",
    "jal	ra, 27b",
    "lw	a0, 28(sp)", // 4-byte Folded Reload
    "beqz	a0, 98f",
    // in Loop: Header=BB16_1 Depth=1
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "j	78f",
    "77:", // .LBB16_4: Parent Loop BB16_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "srli	a1, a0, 8",
    "andi	a2, a1, 255",
    "mul	a2, a2, a5",
    "srli	a2, a2, 9",
    "slli	a3, a2, 3",
    "sub	a1, a1, a2",
    "sub	a1, a1, a3",
    "andi	a1, a1, 255",
    "add	a1, a1, a4",
    "sb	a0, 12(a1)",
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 77b",
    // in Loop: Header=BB16_1 Depth=1
    "addi	a1, a4, 24",
    "lw	a0, 24(sp)", // 4-byte Folded Reload
    "lw	a2, 44(sp)", // 4-byte Folded Reload
    "jal	ra, 27b",
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "li	a0, 1",
    "sw	a0, 28(sp)", // 4-byte Folded Spill
    "78:", // .LBB16_6: in Loop: Header=BB16_1 Depth=1
    "lw	a2, 12(sp)", // 4-byte Folded Reload
    "lbu	a0, 13(a2)",
    "lw	a1, 4(a2)",
    "lw	a3, 8(a2)",
    "li	a2, 730",
    "mul	a0, a0, a2",
    "lw	a2, 16(sp)", // 4-byte Folded Reload
    "mulhu	s0, a1, a2",
    // ERRATA BUG2 patch: lw	a1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a1, 24(sp)",
    "addi sp, sp, 4",
    "mulhu	a0, a0, a1",
    "srli	s0, s0, 3",
    "addi	a1, a0, 70",
    "sub	a0, s0, a3",
    "bgeu	a1, a0, 79f",
    // in Loop: Header=BB16_1 Depth=1
    "sw	s0, 8(a4)",
    "mv	a3, s0",
    "79:", // .LBB16_8: in Loop: Header=BB16_1 Depth=1
    "lui	a0, %hi(102f)",
    "lw	a0, %lo(102f)(a0)",
    "sw	a0, 32(sp)", // 4-byte Folded Spill
    "lw	a0, 100(sp)", // 4-byte Folded Reload
    "beqz	a0, 93f",
    // in Loop: Header=BB16_1 Depth=1
    "sw	a3, 108(sp)", // 4-byte Folded Spill
    "sw	a1, 128(sp)", // 4-byte Folded Spill
    "lbu	a1, 16(a4)",
    "sw	a1, 72(sp)", // 4-byte Folded Spill
    "lbu	a2, 17(a4)",
    "lbu	a0, 18(a4)",
    "andi	a1, a1, 15",
    "sw	a2, 56(sp)", // 4-byte Folded Spill
    "sub	a0, a0, a2",
    "lw	a2, 32(sp)", // 4-byte Folded Reload
    "mul	a1, a2, a1",
    "sw	a1, 104(sp)", // 4-byte Folded Spill
    "slli	a0, a0, 16",
    "lui	a1, 4080",
    "mv	s1, a4",
    "jal	ra, 21b",
    // ERRATA BUG2 patch: lb	a1, 20(s1) (offset=20,bits[4:0]=20)
    "addi s1, s1, -4",
    "lb a1, 24(s1)",
    "addi s1, s1, 4",
    "sw	a1, 96(sp)", // 4-byte Folded Spill
    "lbu	a1, 12(s1)",
    "sw	a1, 92(sp)", // 4-byte Folded Spill
    "lbu	a1, 14(s1)",
    "sw	a1, 88(sp)", // 4-byte Folded Spill
    "lbu	a1, 15(s1)",
    "sw	a1, 52(sp)", // 4-byte Folded Spill
    "lbu	a1, 19(s1)",
    "sw	a1, 84(sp)", // 4-byte Folded Spill
    "sw	a0, 80(sp)", // 4-byte Folded Spill
    "li	a0, 128",
    "lw	a1, 4(sp)", // 4-byte Folded Reload
    "jal	ra, 33b",
    "sw	a0, 76(sp)", // 4-byte Folded Spill
    "li	a0, 175",
    "lw	a1, 72(sp)", // 4-byte Folded Reload
    "bgeu	a0, a1, 80f",
    // in Loop: Header=BB16_1 Depth=1
    "lw	a0, 104(sp)", // 4-byte Folded Reload
    "neg	a0, a0",
    "sw	a0, 104(sp)", // 4-byte Folded Spill
    "80:", // .LBB16_11: in Loop: Header=BB16_1 Depth=1
    "lw	a1, 128(sp)", // 4-byte Folded Reload
    "li	a3, 0",
    "lw	a0, 108(sp)", // 4-byte Folded Reload
    "sub	a0, a0, s0",
    "slli	a1, a1, 16",
    "sw	a1, 72(sp)", // 4-byte Folded Spill
    "slli	a0, a0, 16",
    "srai	a1, a0, 31",
    // ERRATA BUG2 patch: lw	s1, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 120(sp)",
    "addi sp, sp, 4",
    "mulhu	a2, a0, s1",
    "mul	a1, a1, s1",
    "add	a1, a1, a2",
    "lw	a2, 32(sp)", // 4-byte Folded Reload
    "slli	a2, a2, 23",
    "srli	a2, a2, 24",
    "sw	a2, 40(sp)", // 4-byte Folded Spill
    "mul	a0, a0, s1",
    "srli	a0, a0, 16",
    "slli	a1, a1, 16",
    "or	a0, a0, a1",
    "sw	a0, 68(sp)", // 4-byte Folded Spill
    // ERRATA BUG2 patch: lw	a0, 52(sp) (offset=52,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 56(sp)",
    "addi sp, sp, 4",
    "slli	a0, a0, 8",
    "sw	a0, 52(sp)", // 4-byte Folded Spill
    // implicit-def: $x10
    // kill: killed $x10
    "81:", // .LBB16_12: Parent Loop BB16_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB16_21 Depth 3
    "lw	a0, 92(sp)", // 4-byte Folded Reload
    "sw	a3, 128(sp)", // 4-byte Folded Spill
    "mul	a0, a3, a0",
    "slli	a0, a0, 16",
    "srai	a1, a0, 31",
    "mulhu	a2, a0, s1",
    "mul	a0, a0, s1",
    "mul	a1, a1, s1",
    "add	a1, a1, a2",
    "slli	a1, a1, 16",
    "srli	a0, a0, 16",
    "or	a0, a0, a1",
    "lw	a1, 60(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "mv	s0, a0",
    "lw	a0, 68(sp)", // 4-byte Folded Reload
    "lw	a1, 72(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "li	a1, 128",
    "lw	a2, 88(sp)", // 4-byte Folded Reload
    "bltu	a1, a2, 82f",
    // in Loop: Header=BB16_12 Depth=2
    "neg	a0, a0",
    "82:", // .LBB16_14: in Loop: Header=BB16_12 Depth=2
    "add	a0, a0, s0",
    "srai	a1, a0, 31",
    "xor	a0, a0, a1",
    "sub	t1, a0, a1",
    "bltu	t1, s1, 83f",
    // in Loop: Header=BB16_12 Depth=2
    "mv	a0, t1",
    "mv	a1, s1",
    "mv	s0, t1",
    "jal	ra, 21b",
    "lui	a1, 1048560",
    "and	a1, a1, a0",
    "srai	a0, a0, 31",
    "mul	a0, a0, s1",
    "mulhu	a2, a1, s1",
    "mul	a1, a1, s1",
    "add	a0, a0, a2",
    "slli	a0, a0, 16",
    "srli	a1, a1, 16",
    "or	a0, a0, a1",
    "sub	a0, s0, a0",
    "srai	a1, a0, 31",
    "and	a1, a1, s1",
    "add	t1, a0, a1",
    "83:", // .LBB16_16: in Loop: Header=BB16_12 Depth=2
    "li	t0, 16",
    "lw	a3, 104(sp)", // 4-byte Folded Reload
    "lw	a4, 128(sp)", // 4-byte Folded Reload
    "lw	a0, 112(sp)", // 4-byte Folded Reload
    "bge	a0, t1, 84f",
    // in Loop: Header=BB16_12 Depth=2
    "sub	t1, s1, t1",
    "84:", // .LBB16_18: in Loop: Header=BB16_12 Depth=2
    "mv	a0, t1",
    "lw	a1, 124(sp)", // 4-byte Folded Reload
    "blt	t1, a1, 85f",
    // in Loop: Header=BB16_12 Depth=2
    "lw	a0, 112(sp)", // 4-byte Folded Reload
    "sub	a0, a0, t1",
    "85:", // .LBB16_20: in Loop: Header=BB16_12 Depth=2
    "li	s1, 0",
    "li	a2, 0",
    "lw	a1, 76(sp)", // 4-byte Folded Reload
    "mul	a1, a1, a4",
    "add	a1, a1, a3",
    "andi	a1, a1, 511",
    "sltiu	a3, a1, 256",
    "slli	a1, a1, 16",
    "addi	a3, a3, -1",
    "lui	a4, 8176",
    "and	a3, a3, a4",
    "xor	a1, a1, a3",
    "lw	a3, 80(sp)", // 4-byte Folded Reload
    "mulh	t2, a1, a3",
    "lui	a4, %hi(101f)",
    "addi	a4, a4, %lo(101f)",
    "lw	s0, 64(sp)", // 4-byte Folded Reload
    "86:", // .LBB16_21: Parent Loop BB16_1 Depth=1
    // Parent Loop BB16_12 Depth=2
    // =>    This Inner Loop Header: Depth=3
    "lw	a5, 0(a4)",
    "sra	a3, s1, a2",
    "sra	a1, s0, a2",
    "bltz	a0, 87f",
    // in Loop: Header=BB16_21 Depth=3
    "sub	s0, s0, a3",
    "add	s1, s1, a1",
    "sub	a0, a0, a5",
    "j	88f",
    "87:", // .LBB16_23: in Loop: Header=BB16_21 Depth=3
    "add	s0, s0, a3",
    "sub	s1, s1, a1",
    "add	a0, a0, a5",
    "88:", // .LBB16_24: in Loop: Header=BB16_21 Depth=3
    "addi	a2, a2, 1",
    "addi	a4, a4, 4",
    "bne	a2, t0, 86b",
    // in Loop: Header=BB16_12 Depth=2
    "lw	a0, 124(sp)", // 4-byte Folded Reload
    "blt	t1, a0, 89f",
    // in Loop: Header=BB16_12 Depth=2
    "neg	s0, s0",
    "89:", // .LBB16_27: in Loop: Header=BB16_12 Depth=2
    // ERRATA BUG2 patch: lw	s1, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 120(sp)",
    "addi sp, sp, 4",
    "slli	a0, s0, 7",
    "lui	a1, 2032",
    "sub	a1, s0, a1",
    "sub	a0, a0, a1",
    "srli	s0, a0, 16",
    "lw	a0, 96(sp)", // 4-byte Folded Reload
    "bgez	a0, 90f",
    // in Loop: Header=BB16_12 Depth=2
    "andi	a0, s0, 255",
    "mul	s0, a0, a0",
    "srli	s0, s0, 8",
    "90:", // .LBB16_29: in Loop: Header=BB16_12 Depth=2
    "li	a0, 87",
    // ERRATA BUG2 patch: lw	a1, 84(sp) (offset=84,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a1, 88(sp)",
    "addi sp, sp, 4",
    "bltu	a0, a1, 91f",
    // in Loop: Header=BB16_12 Depth=2
    "lw	a0, 40(sp)", // 4-byte Folded Reload
    "lw	a1, 44(sp)", // 4-byte Folded Reload
    "mv	s1, t2",
    "jal	ra, 36b",
    "mv	t2, s1",
    // ERRATA BUG2 patch: lw	s1, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 120(sp)",
    "addi sp, sp, 4",
    "lw	a3, 128(sp)", // 4-byte Folded Reload
    "bne	a0, a3, 91f",
    // in Loop: Header=BB16_12 Depth=2
    "lw	a0, 36(sp)", // 4-byte Folded Reload
    "j	92f",
    "91:", // .LBB16_32: in Loop: Header=BB16_12 Depth=2
    "lw	a0, 56(sp)", // 4-byte Folded Reload
    "add	a0, a0, t2",
    "slli	s0, s0, 24",
    "andi	a0, a0, 255",
    "srli	s0, s0, 8",
    // ERRATA BUG2 patch: lw	a1, 52(sp) (offset=52,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a1, 56(sp)",
    "addi sp, sp, 4",
    "or	a0, a0, a1",
    "lui	a1, 1044480",
    "lw	a2, 108(sp)", // 4-byte Folded Reload
    "and	a1, a1, a2",
    "or	a0, a0, a1",
    "or	a0, a0, s0",
    "sw	a0, 108(sp)", // 4-byte Folded Spill
    "jal	ra, 50b",
    "lw	a3, 128(sp)", // 4-byte Folded Reload
    "slli	a1, a0, 3",
    "srli	a0, a0, 21",
    "lw	a2, 48(sp)", // 4-byte Folded Reload
    "and	a1, a1, a2",
    "or	a0, a0, a1",
    "92:", // .LBB16_33: in Loop: Header=BB16_12 Depth=2
    "slli	a1, a3, 2",
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "add	a1, a1, a4",
    "addi	a3, a3, 1",
    "sw	a0, 32(a1)",
    "lw	a0, 100(sp)", // 4-byte Folded Reload
    "bne	a3, a0, 81b",
    "93:", // .LBB16_34: in Loop: Header=BB16_1 Depth=1
    "sw	zero, 24(a4)",
    "sw	zero, 28(a4)",
    "lw	a2, 44(sp)", // 4-byte Folded Reload
    "94:", // .LBB16_35: in Loop: Header=BB16_1 Depth=1
    "li	a5, 57",
    "lw	a1, 32(sp)", // 4-byte Folded Reload
    "95:", // .LBB16_36: in Loop: Header=BB16_1 Depth=1
    "li	a0, 0",
    "addi	a1, a1, 1",
    "lui	a3, %hi(102f)",
    "sw	a1, %lo(102f)(a3)",
    "li	a3, 35",
    "96:", // .LBB16_37: Parent Loop BB16_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB16_38 Depth 3
    "lw	a1, 120(sp)", // 4-byte Folded Reload
    "97:", // .LBB16_38: Parent Loop BB16_1 Depth=1
    // Parent Loop BB16_37 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 97b",
    // in Loop: Header=BB16_37 Depth=2
    "lw	a1, 4(a4)",
    "addi	a1, a1, 1",
    "addi	a0, a0, 1",
    "sw	a1, 4(a4)",
    "beq	a0, a3, 76b",
    "j	96b",
    "98:", // .LBB16_40: in Loop: Header=BB16_1 Depth=1
    "lui	a0, %hi(102f)",
    "lw	a1, %lo(102f)(a0)",
    "mv	a2, s0",
    "beqz	s0, 100f",
    // in Loop: Header=BB16_1 Depth=1
    "sw	a1, 32(sp)", // 4-byte Folded Spill
    "slli	a0, a1, 23",
    "srli	a0, a0, 24",
    "mv	a1, a2",
    "mv	s0, a2",
    "jal	ra, 36b",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "mv	a2, s0",
    "lw	s0, 0(sp)", // 4-byte Folded Reload
    "99:", // .LBB16_42: Parent Loop BB16_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "snez	a3, a0",
    "addi	a2, a2, -1",
    "addi	a3, a3, -1",
    "and	a3, a3, s0",
    "sw	a3, 0(a1)",
    "addi	a1, a1, 4",
    "addi	a0, a0, -1",
    "bnez	a2, 99b",
    // in Loop: Header=BB16_1 Depth=1
    "lw	a2, 44(sp)", // 4-byte Folded Reload
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "j	94b",
    "100:", // .LBB16_44: in Loop: Header=BB16_1 Depth=1
    "sw	zero, 28(sp)", // 4-byte Folded Spill
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "li	a5, 57",
    "j	95b",
    // --- rodata: cordic_atan_table (16 entries, 16 words) ---
    ".p2align 2",
    "101:", // cordic_atan_table
    ".word 0x0000c910", // [0] 51472
    ".word 0x000076b2", // [4] 30386
    ".word 0x00003eb7", // [8] 16055
    ".word 0x00001fd6", // [12] 8150
    ".word 0x00000ffb", // [16] 4091
    ".word 0x000007ff", // [20] 2047
    ".word 0x00000400", // [24] 1024
    ".word 0x00000200", // [28] 512
    ".word 0x00000100", // [32] 256
    ".word 0x00000080", // [36] 128
    ".word 0x00000040", // [40] 64
    ".word 0x00000020", // [44] 32
    ".word 0x00000010", // [48] 16
    ".word 0x00000008", // [52] 8
    ".word 0x00000004", // [56] 4
    ".word 0x00000002", // [60] 2
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "102:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: time_ms (4 entries, 1 words) ---
    ".p2align 0",
    "103:", // time_ms
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: reftime_lg (4 entries, 1 words) ---
    ".p2align 0",
    "104:", // reftime_lg
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: diploid (12 entries, 3 words) ---
    ".p2align 0",
    "105:", // diploid
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    // --- rodata: led_buf (40 entries, 10 words) ---
    ".p2align 0",
    "106:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000" // [36] 0, 0, 0, 0
);
