// AUTOGENERATED CODE on 2026-03-21T22:45:38.261258 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(lightgenes_bio_code, BM_LIGHTGENES_BIO_START, BM_LIGHTGENES_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	77f",
    // --- inline asm end ---
    "21:", // fp_div: @fp_div
    "lui	a2, 524288",
    "beqz	a1, 26f",
    "srai	a3, a0, 31",
    "srai	a4, a1, 31",
    "xor	a5, a0, a3",
    "sub	t2, a5, a3",
    "xor	a5, a1, a4",
    "sub	a4, a5, a4",
    "lui	a5, 16",
    "bgeu	a4, t2, 23f",
    "22:", // .LBB1_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "slli	a5, a5, 1",
    "bltu	a4, t2, 22b",
    "beqz	a5, 26f",
    "23:", // .LBB1_4
    "srli	t0, a4, 31",
    "srl	t1, a4, t0",
    "li	a4, 0",
    "beqz	a0, 25f",
    "srl	a5, a5, t0",
    "li	t0, 2",
    "24:", // .LBB1_6: =>This Inner Loop Header: Depth=1
    "sltu	a2, t2, t1",
    "addi	a2, a2, -1",
    "and	a3, a2, t1",
    "and	a2, a2, a5",
    "sub	t2, t2, a3",
    "or	a4, a4, a2",
    "slli	t2, t2, 1",
    "bltu	a5, t0, 25f",
    // in Loop: Header=BB1_6 Depth=1
    "srli	a5, a5, 1",
    "bnez	t2, 24b",
    "25:", // .LBB1_8
    "sltu	a2, t2, t1",
    "xori	a2, a2, 1",
    "xor	a0, a0, a1",
    "add	a2, a2, a4",
    "bgez	a0, 26f",
    "neg	a2, a2",
    "26:", // .LBB1_10
    "mv	a0, a2",
    "ret",
    "27:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // __udivsi3: @__udivsi3
    "beqz	a1, 35f",
    "mv	t2, a0",
    "li	a4, 0",
    "li	a0, 0",
    "li	a3, 31",
    "li	t0, 1",
    "li	t1, -1",
    "34:", // .LBB3_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	a5, t2, a3",
    "sll	a2, t0, a3",
    "addi	a3, a3, -1",
    "andi	a5, a5, 1",
    "or	a4, a4, a5",
    "sltu	a5, a4, a1",
    "addi	a5, a5, -1",
    "and	a2, a2, a5",
    "and	a5, a5, a1",
    "or	a0, a0, a2",
    "sub	a4, a4, a5",
    "bne	a3, t1, 34b",
    "ret",
    "35:", // .LBB3_4
    "li	a0, -1",
    "ret",
    "36:", // __umodsi3: @__umodsi3
    "beqz	a1, 38f",
    "li	a2, 0",
    "li	a3, 31",
    "li	a4, -1",
    "37:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a0, a3",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a3, a3, -1",
    "sub	a2, a2, a5",
    "bne	a3, a4, 37b",
    "j	39f",
    "38:", // .LBB4_3
    "mv	a2, a0",
    "39:", // .LBB4_4
    "mv	a0, a2",
    "ret",
    "40:", // __divsi3: @__divsi3
    "addi	sp, sp, -16",
    "sw	s0, 12(sp)", // 4-byte Folded Spill
    "sw	s1, 8(sp)", // 4-byte Folded Spill
    "mv	t0, a0",
    "beqz	a1, 42f",
    "li	a4, 0",
    "li	a0, 0",
    "srai	t2, t0, 31",
    "srai	s0, a1, 31",
    "li	a3, 31",
    "li	t1, 1",
    "xor	a5, t0, t2",
    "sub	a5, a5, t2",
    "xor	a2, a1, s0",
    "sub	a2, a2, s0",
    "li	t2, -1",
    "41:", // .LBB5_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	s0, a5, a3",
    "sll	s1, t1, a3",
    "addi	a3, a3, -1",
    "andi	s0, s0, 1",
    "or	a4, a4, s0",
    "sltu	s0, a4, a2",
    "addi	s0, s0, -1",
    "and	s1, s1, s0",
    "and	s0, s0, a2",
    "or	a0, a0, s1",
    "sub	a4, a4, s0",
    "bne	a3, t2, 41b",
    "j	43f",
    "42:", // .LBB5_3
    "li	a0, -1",
    "43:", // .LBB5_4
    "xor	a1, a1, t0",
    "bgez	a1, 44f",
    "neg	a0, a0",
    "44:", // .LBB5_6
    "lw	s0, 12(sp)", // 4-byte Folded Reload
    "lw	s1, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "45:", // __modsi3: @__modsi3
    "srai	a2, a0, 31",
    "xor	a3, a0, a2",
    "sub	a3, a3, a2",
    "beqz	a1, 49f",
    "li	a2, 0",
    "srai	a5, a1, 31",
    "li	a4, 31",
    "xor	a1, a1, a5",
    "sub	a1, a1, a5",
    "li	t0, -1",
    "46:", // .LBB6_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a3, a4",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a4, a4, -1",
    "sub	a2, a2, a5",
    "bne	a4, t0, 46b",
    "bgez	a0, 48f",
    "47:", // .LBB6_4
    "neg	a2, a2",
    "48:", // .LBB6_5
    "mv	a0, a2",
    "ret",
    "49:", // .LBB6_6
    "mv	a2, a3",
    "bltz	a0, 47b",
    "j	48b",
    "50:", // HsvToRgb: @HsvToRgb
    "slli	a4, a0, 16",
    "srli	a4, a4, 24",
    "srli	a1, a0, 16",
    "beqz	a4, 51f",
    "andi	a2, a0, 255",
    "li	a3, 191",
    "li	t0, 213",
    "andi	a5, a1, 255",
    "mul	a3, a2, a3",
    "xori	a2, a4, 255",
    "mul	a2, a2, a5",
    "srli	a3, a3, 13",
    "srli	t1, a2, 8",
    "mul	a2, a3, t0",
    "add	a0, a0, a2",
    "slli	a2, a0, 1",
    "slli	a0, a0, 3",
    "sub	a0, a0, a2",
    "andi	a0, a0, 254",
    "mul	a2, a0, a4",
    "xori	a0, a0, 255",
    "srli	a2, a2, 8",
    "mul	a0, a0, a4",
    "xori	a2, a2, 255",
    "srli	a0, a0, 8",
    "mul	a2, a2, a5",
    "xori	a4, a0, 255",
    "srli	a0, a2, 8",
    "mul	a5, a4, a5",
    "li	a2, 1",
    "srli	a5, a5, 8",
    "bge	a2, a3, 52f",
    "li	a2, 2",
    "beq	a3, a2, 53f",
    "li	a2, 3",
    "beq	a3, a2, 54f",
    "li	a2, 4",
    "bne	a3, a2, 58f",
    "mv	a3, a5",
    "mv	a4, t1",
    "j	55f",
    "51:", // .LBB7_6
    "mv	a3, a1",
    "mv	a4, a1",
    "j	55f",
    "52:", // .LBB7_7
    "beqz	a3, 56f",
    "li	a2, 1",
    "bne	a3, a2, 58f",
    "mv	a3, a0",
    "mv	a4, a1",
    "j	57f",
    "53:", // .LBB7_10
    "mv	a3, t1",
    "mv	a4, a1",
    "mv	a0, a5",
    "j	59f",
    "54:", // .LBB7_11
    "mv	a3, t1",
    "mv	a4, a0",
    "55:", // .LBB7_12
    "mv	a0, a1",
    "j	59f",
    "56:", // .LBB7_13
    "mv	a3, a1",
    "mv	a4, a5",
    "57:", // .LBB7_14
    "mv	a0, t1",
    "j	59f",
    "58:", // .LBB7_15
    "mv	a3, a1",
    "mv	a4, t1",
    "59:", // .LBB7_16
    "slli	a0, a0, 24",
    "slli	a4, a4, 24",
    "srli	a0, a0, 8",
    "srli	a4, a4, 16",
    "andi	a1, a3, 255",
    "or	a1, a1, a4",
    "or	a0, a0, a1",
    "ret",
    "60:", // satsub_8: @satsub_8
    "sub	a1, a0, a1",
    "sltu	a0, a0, a1",
    "addi	a0, a0, -1",
    "and	a0, a0, a1",
    "ret",
    "61:", // satadd_8: @satadd_8
    "add	a0, a0, a1",
    "li	a1, 255",
    "bltu	a0, a1, 62f",
    "li	a0, 255",
    "62:", // .LBB9_2
    "ret",
    "63:", // satadd_8_limit: @satadd_8_limit
    "add	a0, a0, a1",
    "bltu	a0, a2, 64f",
    "mv	a0, a2",
    "64:", // .LBB10_2
    "ret",
    "65:", // satsub_8p: @satsub_8p
    "andi	a2, a0, 255",
    "slli	a3, a0, 16",
    "slli	a0, a0, 8",
    "srli	a3, a3, 24",
    "srli	a0, a0, 24",
    "sub	a4, a2, a1",
    "sltu	a2, a2, a4",
    "addi	a2, a2, -1",
    "and	a2, a2, a4",
    "sub	a4, a3, a1",
    "sub	a1, a0, a1",
    "sltu	a3, a3, a4",
    "sltu	a0, a0, a1",
    "addi	a3, a3, -1",
    "addi	a0, a0, -1",
    "and	a3, a3, a4",
    "and	a0, a0, a1",
    "slli	a0, a0, 16",
    "slli	a3, a3, 8",
    "or	a0, a0, a3",
    "or	a0, a0, a2",
    "ret",
    "66:", // satadd_8p: @satadd_8p
    "slli	a2, a0, 16",
    "srli	a2, a2, 24",
    "add	a2, a2, a1",
    "li	a3, 255",
    "bltu	a2, a3, 67f",
    "li	a2, 255",
    "67:", // .LBB12_2
    "andi	a4, a0, 255",
    "add	a4, a4, a1",
    "bltu	a4, a3, 68f",
    "li	a4, 255",
    "68:", // .LBB12_4
    "slli	a0, a0, 8",
    "srli	a0, a0, 24",
    "add	a1, a1, a0",
    "bltu	a1, a3, 69f",
    "li	a1, 255",
    "69:", // .LBB12_6
    "slli	a1, a1, 16",
    "slli	a2, a2, 8",
    "or	a0, a1, a2",
    "or	a0, a0, a4",
    "ret",
    "70:", // map_16: @map_16
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "mv	a5, a0",
    "slli	s1, a1, 16",
    "slli	a1, a3, 16",
    "slli	a4, a4, 16",
    "sub	a0, a4, a1",
    "sw	a1, 0(sp)", // 4-byte Folded Spill
    "xor	a1, a1, a4",
    "xor	a4, a4, a0",
    "and	a1, a1, a4",
    "slli	a2, a2, 16",
    "bgez	a1, 71f",
    "lui	a0, 524288",
    "71:", // .LBB13_2
    "sub	a1, a2, s1",
    "xor	a3, a2, s1",
    "xor	a2, a2, a1",
    "and	a2, a2, a3",
    "slli	s0, a5, 16",
    "bgez	a2, 72f",
    "lui	a1, 524288",
    "72:", // .LBB13_4
    "jal	ra, 21b",
    "sub	a1, s0, s1",
    "xor	s1, s1, s0",
    "xor	s0, s0, a1",
    "and	s0, s0, s1",
    "bgez	s0, 73f",
    "lui	a1, 524288",
    "73:", // .LBB13_6
    "mul	a2, a0, a1",
    "mulh	a0, a0, a1",
    "slli	a0, a0, 16",
    "srli	a2, a2, 16",
    "or	a2, a2, a0",
    "lw	a1, 0(sp)", // 4-byte Folded Reload
    "add	a0, a1, a2",
    "xor	a1, a1, a2",
    "slti	a1, a1, 0",
    "xor	a2, a2, a0",
    "slti	a2, a2, 0",
    "xori	a2, a2, 1",
    "or	a1, a1, a2",
    "bnez	a1, 74f",
    "lui	a0, 1048568",
    "j	75f",
    "74:", // .LBB13_8
    "srli	a0, a0, 16",
    "75:", // .LBB13_9
    "slli	a0, a0, 16",
    "srai	a0, a0, 16",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "lw	s1, 4(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "76:", // map: @map
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "mv	s0, a3",
    "sub	a0, a0, a1",
    "sub	a4, a4, a3",
    "mul	a0, a4, a0",
    "sub	a1, a2, a1",
    "jal	ra, 40b",
    "add	a0, a0, s0",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "77:", // main: @main
    "addi	sp, sp, -144",
    "sw	ra, 140(sp)", // 4-byte Folded Spill
    "sw	s0, 136(sp)", // 4-byte Folded Spill
    "sw	s1, 132(sp)", // 4-byte Folded Spill
    "li	a1, 0",
    // ERRATA BUG1 patch: lui	t0, 1048475 (B1:phantom-rs1)
    "lui t0, 0xfff03",
    "sw t0, -4(sp)",
    "addi t0, zero, 19",
    "slli t0, t0, 3",
    "slli t0, t0, 12",
    "add t0, t0, t0",
    "lw t0, -4(sp)",
    // --- inline asm begin ---
    "mv	x27, a1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "sw	a0, 28(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	a3, x17",
    // --- inline asm end ---
    "lui	t1, 1048560",
    "lui	a2, 2",
    "lui	t2, 4112",
    "lui	a4, 50",
    "lui	a5, 25",
    "lui	s1, 10",
    "lui	s0, 2040",
    "lui	a0, 498",
    "addi	a1, t0, 1921",
    "sw	a1, 40(sp)", // 4-byte Folded Spill
    "slli	a1, a3, 16",
    "add	a1, a1, t1",
    "sw	a1, 64(sp)", // 4-byte Folded Spill
    "addi	a1, a2, -892",
    "sw	a1, 24(sp)", // 4-byte Folded Spill
    "addi	a1, t2, 258",
    "sw	a1, 20(sp)", // 4-byte Folded Spill
    "addi	a2, a2, -1522",
    "addi	a1, a4, 1087",
    "sw	a1, 112(sp)", // 4-byte Folded Spill
    "addi	a1, a5, 545",
    "sw	a1, 124(sp)", // 4-byte Folded Spill
    "addi	a1, s1, -1163",
    "sw	a1, 60(sp)", // 4-byte Folded Spill
    "addi	a1, s0, -129",
    "sw	a1, 36(sp)", // 4-byte Folded Spill
    "addi	a0, a0, -256",
    "sw	a0, 48(sp)", // 4-byte Folded Spill
    "lui	a0, 101",
    "lui	a1, %hi(103f)",
    "lui	s0, %hi(103f)",
    "addi	s0, s0, %lo(103f)",
    "addi	a0, a0, -1921",
    "sw	a0, 56(sp)", // 4-byte Folded Spill
    "sw	a3, 116(sp)", // 4-byte Folded Spill
    "srli	a3, a3, 1",
    "sw	a3, 4(sp)", // 4-byte Folded Spill
    "addi	a0, a1, %lo(103f)",
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    "addi	a0, a0, 24",
    "sw	a0, 8(sp)", // 4-byte Folded Spill
    "li	a4, 57",
    "sw	a2, 16(sp)", // 4-byte Folded Spill
    "78:", // .LBB15_1: =>This Loop Header: Depth=1
    // Child Loop BB15_2 Depth 2
    // Child Loop BB15_11 Depth 2
    // Child Loop BB15_22 Depth 3
    // Child Loop BB15_38 Depth 2
    // Child Loop BB15_39 Depth 3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "79:", // .LBB15_2: Parent Loop BB15_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a0, a0, 5",
    "bgez	a0, 80f",
    // in Loop: Header=BB15_2 Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "srli	a1, a0, 8",
    "andi	a2, a1, 255",
    "mul	a2, a2, a4",
    "srli	a2, a2, 9",
    "slli	a3, a2, 3",
    "sub	a1, a1, a2",
    "sub	a1, a1, a3",
    "andi	a1, a1, 255",
    "add	a1, a1, s0",
    "sb	a0, 12(a1)",
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "j	79b",
    "80:", // .LBB15_4: in Loop: Header=BB15_1 Depth=1
    "lw	a0, 28(sp)", // 4-byte Folded Reload
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	a2, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a2, 120(sp)",
    "addi sp, sp, 4",
    "jal	ra, 27b",
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "lbu	a0, 13(a1)",
    "lw	a2, 4(a1)",
    "lw	a3, 8(a1)",
    "lw	a1, 24(sp)", // 4-byte Folded Reload
    "mul	a0, a0, a1",
    // ERRATA BUG2 patch: lw	a1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a1, 24(sp)",
    "addi sp, sp, 4",
    "mulhu	a0, a0, a1",
    "addi	a1, a0, 700",
    "sub	a0, a2, a3",
    "bgeu	a1, a0, 81f",
    // in Loop: Header=BB15_1 Depth=1
    "sw	a2, 8(s0)",
    "mv	a3, a2",
    "81:", // .LBB15_6: in Loop: Header=BB15_1 Depth=1
    "lui	a0, %hi(103f)",
    "lw	a0, %lo(103f)(a0)",
    "sw	a0, 32(sp)", // 4-byte Folded Spill
    // ERRATA BUG2 patch: lw	a0, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 120(sp)",
    "addi sp, sp, 4",
    "beqz	a0, 99f",
    // in Loop: Header=BB15_1 Depth=1
    "sw	a3, 108(sp)", // 4-byte Folded Spill
    "sw	a1, 120(sp)", // 4-byte Folded Spill
    "sw	a2, 128(sp)", // 4-byte Folded Spill
    "lbu	a0, 12(s0)",
    "sw	a0, 104(sp)", // 4-byte Folded Spill
    "lbu	a0, 14(s0)",
    "sw	a0, 100(sp)", // 4-byte Folded Spill
    "lbu	a0, 15(s0)",
    "sw	a0, 52(sp)", // 4-byte Folded Spill
    "mv	a0, s0",
    "lbu	s0, 16(s0)",
    "lbu	a1, 17(a0)",
    "sw	a1, 96(sp)", // 4-byte Folded Spill
    "lbu	a1, 18(a0)",
    "sw	a1, 92(sp)", // 4-byte Folded Spill
    "lbu	a1, 19(a0)",
    "sw	a1, 88(sp)", // 4-byte Folded Spill
    // ERRATA BUG2 patch: lb	a0, 20(a0) (offset=20,bits[4:0]=20)
    "addi t0, a0, -4",
    "lb a0, 24(t0)",
    "sw	a0, 84(sp)", // 4-byte Folded Spill
    "andi	a0, s0, 15",
    "lw	a1, 32(sp)", // 4-byte Folded Reload
    "mul	s1, a1, a0",
    "li	a0, 128",
    "lw	a1, 4(sp)", // 4-byte Folded Reload
    "jal	ra, 33b",
    "sw	a0, 76(sp)", // 4-byte Folded Spill
    "li	a0, 175",
    "bltu	a0, s0, 82f",
    // in Loop: Header=BB15_1 Depth=1
    "mv	a2, s1",
    "j	83f",
    "82:", // .LBB15_9: in Loop: Header=BB15_1 Depth=1
    "neg	a2, s1",
    "83:", // .LBB15_10: in Loop: Header=BB15_1 Depth=1
    "lw	a1, 120(sp)", // 4-byte Folded Reload
    "lw	a3, 108(sp)", // 4-byte Folded Reload
    "li	s1, 0",
    "lw	a0, 128(sp)", // 4-byte Folded Reload
    "sub	a0, a3, a0",
    "slli	a1, a1, 16",
    "sw	a1, 72(sp)", // 4-byte Folded Spill
    "lw	a1, 32(sp)", // 4-byte Folded Reload
    "slli	a1, a1, 23",
    "slli	a0, a0, 16",
    "sw	a0, 68(sp)", // 4-byte Folded Spill
    "srli	a1, a1, 24",
    "sw	a1, 44(sp)", // 4-byte Folded Spill
    // ERRATA BUG2 patch: lw	a0, 52(sp) (offset=52,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 56(sp)",
    "addi sp, sp, 4",
    "slli	a0, a0, 8",
    "sw	a0, 52(sp)", // 4-byte Folded Spill
    // implicit-def: $x10
    // kill: killed $x10
    "sw	a2, 80(sp)", // 4-byte Folded Spill
    "84:", // .LBB15_11: Parent Loop BB15_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB15_22 Depth 3
    "lw	a0, 76(sp)", // 4-byte Folded Reload
    "mul	a0, a0, s1",
    "add	a0, a0, a2",
    "andi	a0, a0, 511",
    "sltiu	a1, a0, 256",
    "addi	a1, a1, -1",
    "andi	a1, a1, 511",
    "xor	a0, a0, a1",
    "li	a2, 255",
    "li	a1, 0",
    "lw	a3, 96(sp)", // 4-byte Folded Reload
    "lw	a4, 92(sp)", // 4-byte Folded Reload
    "jal	ra, 70b",
    "sw	a0, 120(sp)", // 4-byte Folded Spill
    "sw	s1, 128(sp)", // 4-byte Folded Spill
    "slli	a0, s1, 16",
    "lw	a1, 64(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "lw	a1, 104(sp)", // 4-byte Folded Reload
    "mul	a0, a1, a0",
    "srai	a1, a0, 31",
    "lw	s0, 56(sp)", // 4-byte Folded Reload
    "mulhu	a2, a0, s0",
    "mul	a0, a0, s0",
    "mul	a1, a1, s0",
    "add	a1, a1, a2",
    "slli	a1, a1, 16",
    "srli	a0, a0, 16",
    "or	s1, a0, a1",
    "lw	a0, 68(sp)", // 4-byte Folded Reload
    "lw	a1, 72(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "srai	a1, a0, 31",
    "mulhu	a2, a0, s0",
    "mul	a0, a0, s0",
    "mul	a1, a1, s0",
    "add	a1, a1, a2",
    "slli	a1, a1, 16",
    "srli	a0, a0, 16",
    "or	a0, a0, a1",
    "xor	a1, s1, a0",
    "li	a2, 129",
    "lw	a3, 100(sp)", // 4-byte Folded Reload
    "bltu	a3, a2, 85f",
    // in Loop: Header=BB15_11 Depth=2
    "add	a0, a0, s1",
    "slti	a1, a1, 0",
    "xor	s1, s1, a0",
    "slti	a2, s1, 0",
    "xori	a2, a2, 1",
    "or	a1, a1, a2",
    "beqz	a1, 86f",
    "j	87f",
    "85:", // .LBB15_13: in Loop: Header=BB15_11 Depth=2
    "sub	a0, s1, a0",
    "xor	s1, s1, a0",
    "and	a1, a1, s1",
    "bgez	a1, 87f",
    "86:", // .LBB15_14: in Loop: Header=BB15_11 Depth=2
    "lui	a0, 524288",
    "87:", // .LBB15_15: in Loop: Header=BB15_11 Depth=2
    "srai	a1, a0, 31",
    "xor	a0, a0, a1",
    "sub	t1, a0, a1",
    "bltu	t1, s0, 88f",
    // in Loop: Header=BB15_11 Depth=2
    "mv	a0, t1",
    "mv	a1, s0",
    "mv	s1, t1",
    "jal	ra, 21b",
    "srai	a0, a0, 16",
    "lw	a2, 40(sp)", // 4-byte Folded Reload
    "mul	a0, a0, a2",
    "add	a0, a0, s1",
    "lui	a1, 101",
    "addi	a1, a1, -1922",
    "slt	a1, a1, a0",
    "neg	a1, a1",
    "and	a1, a1, a2",
    "add	t1, a0, a1",
    "88:", // .LBB15_17: in Loop: Header=BB15_11 Depth=2
    "li	t0, 16",
    "lw	a0, 112(sp)", // 4-byte Folded Reload
    "bge	a0, t1, 89f",
    // in Loop: Header=BB15_11 Depth=2
    "sub	t1, s0, t1",
    "89:", // .LBB15_19: in Loop: Header=BB15_11 Depth=2
    "mv	a1, t1",
    "lw	a0, 124(sp)", // 4-byte Folded Reload
    "blt	t1, a0, 90f",
    // in Loop: Header=BB15_11 Depth=2
    "lw	a0, 112(sp)", // 4-byte Folded Reload
    "sub	a1, a0, t1",
    "90:", // .LBB15_21: in Loop: Header=BB15_11 Depth=2
    "li	s0, 0",
    "li	a3, 0",
    "lui	a4, %hi(102f)",
    "addi	a4, a4, %lo(102f)",
    "lw	s1, 60(sp)", // 4-byte Folded Reload
    "91:", // .LBB15_22: Parent Loop BB15_1 Depth=1
    // Parent Loop BB15_11 Depth=2
    // =>    This Inner Loop Header: Depth=3
    "lw	a5, 0(a4)",
    "sra	a0, s0, a3",
    "sra	a2, s1, a3",
    "bltz	a1, 92f",
    // in Loop: Header=BB15_22 Depth=3
    "sub	s1, s1, a0",
    "add	s0, s0, a2",
    "sub	a1, a1, a5",
    "j	93f",
    "92:", // .LBB15_24: in Loop: Header=BB15_22 Depth=3
    "add	s1, s1, a0",
    "sub	s0, s0, a2",
    "add	a1, a1, a5",
    "93:", // .LBB15_25: in Loop: Header=BB15_22 Depth=3
    "addi	a3, a3, 1",
    "addi	a4, a4, 4",
    "bne	a3, t0, 91b",
    // in Loop: Header=BB15_11 Depth=2
    "lw	a0, 124(sp)", // 4-byte Folded Reload
    "blt	t1, a0, 94f",
    // in Loop: Header=BB15_11 Depth=2
    "neg	s1, s1",
    "94:", // .LBB15_28: in Loop: Header=BB15_11 Depth=2
    "lui	s0, %hi(103f)",
    "addi	s0, s0, %lo(103f)",
    "lui	a0, 524272",
    "blt	s1, a0, 95f",
    // in Loop: Header=BB15_11 Depth=2
    "lui	s1, 524272",
    "95:", // .LBB15_30: in Loop: Header=BB15_11 Depth=2
    "slli	a0, s1, 7",
    "lui	a1, 2032",
    "sub	a1, s1, a1",
    "sub	a0, a0, a1",
    "srli	s1, a0, 16",
    // ERRATA BUG2 patch: lw	a0, 84(sp) (offset=84,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 88(sp)",
    "addi sp, sp, 4",
    "bgez	a0, 96f",
    // in Loop: Header=BB15_11 Depth=2
    "andi	a0, s1, 255",
    "mul	s1, a0, a0",
    "srli	s1, s1, 8",
    "96:", // .LBB15_32: in Loop: Header=BB15_11 Depth=2
    "li	a0, 89",
    "lw	a1, 88(sp)", // 4-byte Folded Reload
    "bltu	a0, a1, 97f",
    // in Loop: Header=BB15_11 Depth=2
    "lw	a0, 44(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	a1, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a1, 120(sp)",
    "addi sp, sp, 4",
    "jal	ra, 36b",
    "lw	a1, 128(sp)", // 4-byte Folded Reload
    "bne	a0, a1, 97f",
    // in Loop: Header=BB15_11 Depth=2
    "lw	a0, 36(sp)", // 4-byte Folded Reload
    "j	98f",
    "97:", // .LBB15_35: in Loop: Header=BB15_11 Depth=2
    "lbu	a0, 120(sp)", // 4-byte Folded Reload
    "slli	s1, s1, 24",
    "srli	s1, s1, 8",
    // ERRATA BUG2 patch: lw	a1, 52(sp) (offset=52,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a1, 56(sp)",
    "addi sp, sp, 4",
    "or	a0, a0, a1",
    "lui	a1, 1044480",
    "lw	a2, 108(sp)", // 4-byte Folded Reload
    "and	a1, a1, a2",
    "or	a0, a0, a1",
    "or	a0, a0, s1",
    "sw	a0, 108(sp)", // 4-byte Folded Spill
    "jal	ra, 50b",
    "srli	a1, a0, 19",
    "slli	a0, a0, 5",
    "lw	a2, 48(sp)", // 4-byte Folded Reload
    "and	a0, a0, a2",
    "or	a0, a0, a1",
    "98:", // .LBB15_36: in Loop: Header=BB15_11 Depth=2
    "lw	a2, 80(sp)", // 4-byte Folded Reload
    "lw	s1, 128(sp)", // 4-byte Folded Reload
    "slli	a1, s1, 2",
    "add	a1, a1, s0",
    "addi	s1, s1, 1",
    "sw	a0, 24(a1)",
    // ERRATA BUG2 patch: lw	a0, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 120(sp)",
    "addi sp, sp, 4",
    "bne	s1, a0, 84b",
    "99:", // .LBB15_37: in Loop: Header=BB15_1 Depth=1
    "li	a0, 0",
    "lw	a1, 32(sp)", // 4-byte Folded Reload
    "addi	a1, a1, 1",
    "lui	a2, %hi(103f)",
    "sw	a1, %lo(103f)(a2)",
    "lw	a2, 16(sp)", // 4-byte Folded Reload
    "li	a3, 35",
    "li	a4, 57",
    "100:", // .LBB15_38: Parent Loop BB15_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB15_39 Depth 3
    "mv	a1, a2",
    "101:", // .LBB15_39: Parent Loop BB15_1 Depth=1
    // Parent Loop BB15_38 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 101b",
    // in Loop: Header=BB15_38 Depth=2
    "lw	a1, 4(s0)",
    "addi	a1, a1, 1",
    "addi	a0, a0, 1",
    "sw	a1, 4(s0)",
    "beq	a0, a3, 78b",
    "j	100b",
    // --- rodata: cordic_atan_table (16 entries, 16 words) ---
    ".p2align 2",
    "102:", // cordic_atan_table
    ".word 0x0000c910", // [0] 51472
    ".word 0x000076b2", // [4] 30386
    ".word 0x00003eb7", // [8] 16055
    ".word 0x00001fd6", // [12] 8150
    ".word 0x00000ffb", // [16] 4091
    ".word 0x000007ff", // [20] 2047
    ".word 0x00000400", // [24] 1024
    ".word 0x00000200", // [28] 512
    ".word 0x00000100", // [32] 256
    ".word 0x00000080", // [36] 128
    ".word 0x00000040", // [40] 64
    ".word 0x00000020", // [44] 32
    ".word 0x00000010", // [48] 16
    ".word 0x00000008", // [52] 8
    ".word 0x00000004", // [56] 4
    ".word 0x00000002", // [60] 2
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "103:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: time_ms (4 entries, 1 words) ---
    ".p2align 0",
    "104:", // time_ms
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: reftime_lg (4 entries, 1 words) ---
    ".p2align 0",
    "105:", // reftime_lg
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: diploid (12 entries, 3 words) ---
    ".p2align 0",
    "106:", // diploid
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "107:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
