// AUTOGENERATED CODE on 2026-04-24T01:43:29.573447 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(lightgenes_bio_code, BM_LIGHTGENES_BIO_START, BM_LIGHTGENES_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	79f",
    // --- inline asm end ---
    "21:", // fp_div: @fp_div
    "beqz	a1, 27f",
    "srai	a2, a0, 31",
    "srai	a3, a1, 31",
    "xor	a4, a0, a2",
    "sub	t2, a4, a2",
    "xor	a4, a1, a3",
    "sub	a4, a4, a3",
    "lui	a5, 16",
    "bgeu	a4, t2, 23f",
    "22:", // .LBB1_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "slli	a5, a5, 1",
    "bltu	a4, t2, 22b",
    "23:", // .LBB1_3
    "li	a3, 0",
    "srli	t0, a4, 31",
    "srl	t1, a4, t0",
    "beqz	a5, 25f",
    "beqz	a0, 25f",
    "li	a3, 0",
    "srl	a5, a5, t0",
    "li	t0, 2",
    "24:", // .LBB1_6: =>This Inner Loop Header: Depth=1
    "sltu	a4, t2, t1",
    "addi	a4, a4, -1",
    "and	a2, a4, t1",
    "and	a4, a4, a5",
    "sub	t2, t2, a2",
    "or	a3, a3, a4",
    "slli	t2, t2, 1",
    "bltu	a5, t0, 25f",
    // in Loop: Header=BB1_6 Depth=1
    "srli	a5, a5, 1",
    "bnez	t2, 24b",
    "25:", // .LBB1_8
    "sltu	a2, t2, t1",
    "xori	a2, a2, 1",
    "xor	a1, a1, a0",
    "add	a0, a3, a2",
    "bgez	a1, 26f",
    "neg	a0, a0",
    "26:", // .LBB1_10
    "ret",
    "27:", // .LBB1_11
    "lui	a0, 524288",
    "ret",
    "28:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 33f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 33f",
    "li	t0, 0",
    "29:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "li	a4, 24",
    "30:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 31f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	32f",
    "31:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "32:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 30b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 29b",
    "33:", // .LBB2_9
    "ret",
    "34:", // __udivsi3: @__udivsi3
    "beqz	a1, 36f",
    "mv	t2, a0",
    "li	a4, 0",
    "li	a0, 0",
    "li	a3, 31",
    "li	t0, 1",
    "li	t1, -1",
    "35:", // .LBB3_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	a5, t2, a3",
    "sll	a2, t0, a3",
    "addi	a3, a3, -1",
    "andi	a5, a5, 1",
    "or	a4, a4, a5",
    "sltu	a5, a4, a1",
    "addi	a5, a5, -1",
    "and	a2, a2, a5",
    "and	a5, a5, a1",
    "or	a0, a0, a2",
    "sub	a4, a4, a5",
    "bne	a3, t1, 35b",
    "ret",
    "36:", // .LBB3_4
    "li	a0, -1",
    "ret",
    "37:", // __umodsi3: @__umodsi3
    "beqz	a1, 39f",
    "li	a2, 0",
    "li	a3, 31",
    "li	a4, -1",
    "38:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a0, a3",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a3, a3, -1",
    "sub	a2, a2, a5",
    "bne	a3, a4, 38b",
    "j	40f",
    "39:", // .LBB4_3
    "mv	a2, a0",
    "40:", // .LBB4_4
    "mv	a0, a2",
    "ret",
    "41:", // __divsi3: @__divsi3
    "addi	sp, sp, -16",
    "sw	s0, 12(sp)", // 4-byte Folded Spill
    "sw	s1, 8(sp)", // 4-byte Folded Spill
    "mv	t0, a0",
    "beqz	a1, 43f",
    "li	a4, 0",
    "li	a0, 0",
    "srai	t2, t0, 31",
    "srai	s0, a1, 31",
    "li	a3, 31",
    "li	t1, 1",
    "xor	a5, t0, t2",
    "sub	a5, a5, t2",
    "xor	a2, a1, s0",
    "sub	a2, a2, s0",
    "li	t2, -1",
    "42:", // .LBB5_2: =>This Inner Loop Header: Depth=1
    "slli	a4, a4, 1",
    "srl	s0, a5, a3",
    "sll	s1, t1, a3",
    "addi	a3, a3, -1",
    "andi	s0, s0, 1",
    "or	a4, a4, s0",
    "sltu	s0, a4, a2",
    "addi	s0, s0, -1",
    "and	s1, s1, s0",
    "and	s0, s0, a2",
    "or	a0, a0, s1",
    "sub	a4, a4, s0",
    "bne	a3, t2, 42b",
    "j	44f",
    "43:", // .LBB5_3
    "li	a0, -1",
    "44:", // .LBB5_4
    "xor	a1, a1, t0",
    "bgez	a1, 45f",
    "neg	a0, a0",
    "45:", // .LBB5_6
    "lw	s0, 12(sp)", // 4-byte Folded Reload
    "lw	s1, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "46:", // __modsi3: @__modsi3
    "srai	a2, a0, 31",
    "xor	a3, a0, a2",
    "sub	a3, a3, a2",
    "beqz	a1, 50f",
    "li	a2, 0",
    "srai	a5, a1, 31",
    "li	a4, 31",
    "xor	a1, a1, a5",
    "sub	a1, a1, a5",
    "li	t0, -1",
    "47:", // .LBB6_2: =>This Inner Loop Header: Depth=1
    "slli	a2, a2, 1",
    "srl	a5, a3, a4",
    "andi	a5, a5, 1",
    "or	a2, a2, a5",
    "sltu	a5, a2, a1",
    "addi	a5, a5, -1",
    "and	a5, a5, a1",
    "addi	a4, a4, -1",
    "sub	a2, a2, a5",
    "bne	a4, t0, 47b",
    "bgez	a0, 49f",
    "48:", // .LBB6_4
    "neg	a2, a2",
    "49:", // .LBB6_5
    "mv	a0, a2",
    "ret",
    "50:", // .LBB6_6
    "mv	a2, a3",
    "bltz	a0, 48b",
    "j	49b",
    "51:", // HsvToRgb: @HsvToRgb
    "slli	a4, a0, 16",
    "srli	a4, a4, 24",
    "srli	a1, a0, 16",
    "beqz	a4, 52f",
    "andi	a2, a0, 255",
    "li	a3, 191",
    "li	t0, 213",
    "andi	a5, a1, 255",
    "mul	a3, a2, a3",
    "xori	a2, a4, 255",
    "mul	a2, a2, a5",
    "srli	a3, a3, 13",
    "srli	t1, a2, 8",
    "mul	a2, a3, t0",
    "add	a0, a0, a2",
    "slli	a2, a0, 1",
    "slli	a0, a0, 3",
    "sub	a0, a0, a2",
    "andi	a0, a0, 254",
    "mul	a2, a0, a4",
    "xori	a0, a0, 255",
    "srli	a2, a2, 8",
    "mul	a0, a0, a4",
    "xori	a2, a2, 255",
    "srli	a0, a0, 8",
    "mul	a2, a2, a5",
    "xori	a4, a0, 255",
    "srli	a0, a2, 8",
    "mul	a5, a4, a5",
    "li	a2, 1",
    "srli	a5, a5, 8",
    "bge	a2, a3, 53f",
    "li	a2, 2",
    "beq	a3, a2, 54f",
    "li	a2, 3",
    "beq	a3, a2, 55f",
    "li	a2, 4",
    "bne	a3, a2, 59f",
    "mv	a3, a5",
    "mv	a4, t1",
    "j	56f",
    "52:", // .LBB7_6
    "mv	a3, a1",
    "mv	a4, a1",
    "j	56f",
    "53:", // .LBB7_7
    "beqz	a3, 57f",
    "li	a2, 1",
    "bne	a3, a2, 59f",
    "mv	a3, a0",
    "mv	a4, a1",
    "j	58f",
    "54:", // .LBB7_10
    "mv	a3, t1",
    "mv	a4, a1",
    "mv	a0, a5",
    "j	60f",
    "55:", // .LBB7_11
    "mv	a3, t1",
    "mv	a4, a0",
    "56:", // .LBB7_12
    "mv	a0, a1",
    "j	60f",
    "57:", // .LBB7_13
    "mv	a3, a1",
    "mv	a4, a5",
    "58:", // .LBB7_14
    "mv	a0, t1",
    "j	60f",
    "59:", // .LBB7_15
    "mv	a3, a1",
    "mv	a4, t1",
    "60:", // .LBB7_16
    "slli	a0, a0, 24",
    "slli	a4, a4, 24",
    "srli	a0, a0, 8",
    "srli	a4, a4, 16",
    "andi	a1, a3, 255",
    "or	a1, a1, a4",
    "or	a0, a0, a1",
    "ret",
    "61:", // satsub_8: @satsub_8
    "sub	a1, a0, a1",
    "sltu	a0, a0, a1",
    "addi	a0, a0, -1",
    "and	a0, a0, a1",
    "ret",
    "62:", // satadd_8: @satadd_8
    "add	a0, a0, a1",
    "li	a1, 255",
    "bltu	a0, a1, 63f",
    "li	a0, 255",
    "63:", // .LBB9_2
    "ret",
    "64:", // satadd_8_limit: @satadd_8_limit
    "add	a0, a0, a1",
    "bltu	a0, a2, 65f",
    "mv	a0, a2",
    "65:", // .LBB10_2
    "ret",
    "66:", // satsub_8p: @satsub_8p
    "andi	a2, a0, 255",
    "slli	a3, a0, 16",
    "slli	a0, a0, 8",
    "srli	a3, a3, 24",
    "srli	a0, a0, 24",
    "sub	a4, a2, a1",
    "sltu	a2, a2, a4",
    "addi	a2, a2, -1",
    "and	a2, a2, a4",
    "sub	a4, a3, a1",
    "sub	a1, a0, a1",
    "sltu	a3, a3, a4",
    "sltu	a0, a0, a1",
    "addi	a3, a3, -1",
    "addi	a0, a0, -1",
    "and	a3, a3, a4",
    "and	a0, a0, a1",
    "slli	a0, a0, 16",
    "slli	a3, a3, 8",
    "or	a0, a0, a3",
    "or	a0, a0, a2",
    "ret",
    "67:", // satadd_8p: @satadd_8p
    "slli	a2, a0, 16",
    "srli	a2, a2, 24",
    "add	a2, a2, a1",
    "li	a3, 255",
    "bltu	a2, a3, 68f",
    "li	a2, 255",
    "68:", // .LBB12_2
    "andi	a4, a0, 255",
    "add	a4, a4, a1",
    "bltu	a4, a3, 69f",
    "li	a4, 255",
    "69:", // .LBB12_4
    "slli	a0, a0, 8",
    "srli	a0, a0, 24",
    "add	a1, a1, a0",
    "bltu	a1, a3, 70f",
    "li	a1, 255",
    "70:", // .LBB12_6
    "slli	a1, a1, 16",
    "slli	a2, a2, 8",
    "or	a0, a1, a2",
    "or	a0, a0, a4",
    "ret",
    "71:", // map_16: @map_16
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "mv	s0, a3",
    "mv	s1, a1",
    "sw	a0, 0(sp)", // 4-byte Folded Spill
    "sub	a0, a4, a3",
    "sub	a1, a2, a1",
    "slli	a0, a0, 16",
    "slli	a1, a1, 16",
    "jal	ra, 21b",
    "lw	a1, 0(sp)", // 4-byte Folded Reload
    "sub	a1, a1, s1",
    "slli	a1, a1, 16",
    "mulh	a0, a0, a1",
    "add	a0, a0, s0",
    "slli	a0, a0, 16",
    "srai	a0, a0, 16",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "lw	s1, 4(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "72:", // map: @map
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "mv	s0, a3",
    "sub	a0, a0, a1",
    "sub	a4, a4, a3",
    "mul	a0, a4, a0",
    "sub	a1, a2, a1",
    "jal	ra, 41b",
    "add	a0, a0, s0",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "ret",
    "73:", // test_pattern: @test_pattern
    "beqz	a0, 78f",
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "mv	s0, a0",
    "lui	s1, %hi(111f)",
    "addi	s1, s1, %lo(111f)",
    "lw	a0, 4(s1)",
    "slli	a0, a0, 23",
    "srli	a0, a0, 24",
    "mv	a1, s0",
    "jal	ra, 37b",
    "slli	a3, a0, 2",
    "addi	a1, s1, 28",
    "li	t0, 2",
    "lui	a2, 16",
    "lui	a5, 96",
    "add	a3, a3, a1",
    "addi	a4, a2, 257",
    "addi	a5, a5, 1542",
    "mv	a2, a0",
    "74:", // .LBB15_2: =>This Inner Loop Header: Depth=1
    "beqz	a2, 75f",
    // in Loop: Header=BB15_2 Depth=1
    "sw	zero, 0(a1)",
    "j	77f",
    "75:", // .LBB15_4: in Loop: Header=BB15_2 Depth=1
    "bltu	a0, t0, 76f",
    // in Loop: Header=BB15_2 Depth=1
    "sw	a4, 0(a3)",
    "j	77f",
    "76:", // .LBB15_6: in Loop: Header=BB15_2 Depth=1
    "sw	a5, 0(a3)",
    "77:", // .LBB15_7: in Loop: Header=BB15_2 Depth=1
    "addi	s0, s0, -1",
    "addi	a2, a2, -1",
    "addi	a1, a1, 4",
    "bnez	s0, 74b",
    "lw	ra, 12(sp)", // 4-byte Folded Reload
    "lw	s0, 8(sp)", // 4-byte Folded Reload
    "lw	s1, 4(sp)", // 4-byte Folded Reload
    "addi	sp, sp, 16",
    "78:", // .LBB15_9
    "ret",
    "79:", // main: @main
    "addi	sp, sp, -176",
    "sw	ra, 172(sp)", // 4-byte Folded Spill
    "sw	s0, 168(sp)", // 4-byte Folded Spill
    "sw	s1, 164(sp)", // 4-byte Folded Spill
    "li	a2, 0",
    "sw	zero, 40(sp)", // 4-byte Folded Spill
    "lui	t0, 101",
    "li	t1, 31",
    // --- inline asm begin ---
    "mv	x27, a2",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a2, x17",
    // --- inline asm end ---
    "sw	a2, 16(sp)", // 4-byte Folded Spill
    // --- inline asm begin ---
    "mv	a1, x17",
    // --- inline asm end ---
    "lui	a2, 1048528",
    "lui	a3, 2",
    "lui	a4, 4112",
    "lui	a5, 838861",
    "lui	s1, 50",
    "slli	s0, a1, 16",
    "add	a2, a2, s0",
    "sw	a2, 80(sp)", // 4-byte Folded Spill
    "li	s0, 0",
    "lui	a2, 25",
    "addi	a0, t0, -1921",
    "sw	a0, 128(sp)", // 4-byte Folded Spill
    "slli	t1, t1, 8",
    "sw	t1, 24(sp)", // 4-byte Folded Spill
    "addi	a0, a3, -1522",
    "addi	a3, a4, 258",
    "sw	a3, 32(sp)", // 4-byte Folded Spill
    "addi	a3, a5, -819",
    "sw	a3, 28(sp)", // 4-byte Folded Spill
    "addi	a3, s1, 1087",
    "sw	a3, 148(sp)", // 4-byte Folded Spill
    "mv	s1, a0",
    "addi	a0, a2, 545",
    "sw	a0, 160(sp)", // 4-byte Folded Spill
    "lui	a0, 10",
    "addi	a0, a0, -1163",
    "sw	a0, 76(sp)", // 4-byte Folded Spill
    "lui	a0, 96",
    "addi	a0, a0, 1542",
    "sw	a0, 52(sp)", // 4-byte Folded Spill
    "lui	a4, %hi(111f)",
    "addi	a4, a4, %lo(111f)",
    "lui	a5, %hi(111f)",
    "sw	a1, 36(sp)", // 4-byte Folded Spill
    "addi	a1, a1, -2",
    "addi	a0, a4, 28",
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    "sw	a1, 152(sp)", // 4-byte Folded Spill
    "srli	a1, a1, 1",
    "sw	a1, 124(sp)", // 4-byte Folded Spill
    "lui	a3, 196608",
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "80:", // .LBB16_1: =>This Loop Header: Depth=1
    // Child Loop BB16_2 Depth 2
    // Child Loop BB16_3 Depth 3
    // Child Loop BB16_19 Depth 2
    // Child Loop BB16_28 Depth 3
    // Child Loop BB16_49 Depth 2
    // Child Loop BB16_50 Depth 3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "81:", // .LBB16_2: Parent Loop BB16_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB16_3 Depth 3
    "slli	a0, a0, 5",
    "bgez	a0, 86f",
    "82:", // .LBB16_3: Parent Loop BB16_1 Depth=1
    // Parent Loop BB16_2 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 83f",
    // in Loop: Header=BB16_3 Depth=3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	s0, 3",
    "bgez	a0, 87f",
    "j	82b",
    "83:", // .LBB16_5: in Loop: Header=BB16_2 Depth=2
    "and	a1, a0, a3",
    "beqz	a1, 84f",
    // in Loop: Header=BB16_2 Depth=2
    "slli	a0, a0, 2",
    "srli	a0, a0, 31",
    "sb	a0, %lo(111f)(a5)",
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "j	81b",
    "84:", // .LBB16_7: in Loop: Header=BB16_2 Depth=2
    "srli	a1, a0, 30",
    "beqz	a1, 85f",
    // in Loop: Header=BB16_2 Depth=2
    "srli	a1, a0, 8",
    "andi	a2, a1, 255",
    "li	a3, 57",
    "mul	a2, a2, a3",
    "srli	a2, a2, 9",
    "slli	a3, a2, 3",
    "sub	a1, a1, a2",
    "sub	a1, a1, a3",
    "lui	a3, 196608",
    "andi	a1, a1, 255",
    "add	a1, a1, a4",
    "sb	a0, 16(a1)",
    "li	a0, 1",
    "sw	a0, 40(sp)", // 4-byte Folded Spill
    "85:", // .LBB16_9: in Loop: Header=BB16_2 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "j	81b",
    "86:", // .LBB16_10: in Loop: Header=BB16_1 Depth=1
    "bnez	s0, 87f",
    // in Loop: Header=BB16_1 Depth=1
    "lw	a0, 16(sp)", // 4-byte Folded Reload
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "lw	a2, 36(sp)", // 4-byte Folded Reload
    "jal	ra, 28b",
    "lui	a4, %hi(111f)",
    "addi	a4, a4, %lo(111f)",
    "87:", // .LBB16_12: in Loop: Header=BB16_1 Depth=1
    "lw	a0, 40(sp)", // 4-byte Folded Reload
    "beqz	a0, 104f",
    // in Loop: Header=BB16_1 Depth=1
    "sw	s0, 44(sp)", // 4-byte Folded Spill
    "lbu	a0, 17(a4)",
    "lw	a1, 8(a4)",
    "lw	a3, 12(a4)",
    "li	a2, 640",
    "mul	a0, a0, a2",
    "lw	a2, 28(sp)", // 4-byte Folded Reload
    "mulhu	s0, a1, a2",
    "lw	a1, 32(sp)", // 4-byte Folded Reload
    "mulhu	a0, a0, a1",
    "srli	s0, s0, 3",
    "addi	a1, a0, 60",
    "sub	a0, s0, a3",
    "bgeu	a1, a0, 88f",
    // in Loop: Header=BB16_1 Depth=1
    "sw	s0, 12(a4)",
    "mv	a3, s0",
    "88:", // .LBB16_15: in Loop: Header=BB16_1 Depth=1
    "lw	a2, 4(a4)",
    "lw	a0, 152(sp)", // 4-byte Folded Reload
    "sw	a2, 48(sp)", // 4-byte Folded Spill
    "beqz	a0, 105f",
    // in Loop: Header=BB16_1 Depth=1
    "sw	a3, 144(sp)", // 4-byte Folded Spill
    "sw	a1, 156(sp)", // 4-byte Folded Spill
    // ERRATA BUG2 patch: lbu	a1, 20(a4) (offset=20,bits[4:0]=20)
    "addi a4, a4, -4",
    "lbu a1, 24(a4)",
    "addi a4, a4, 4",
    "sw	a1, 136(sp)", // 4-byte Folded Spill
    "lbu	a3, 21(a4)",
    "lbu	a0, 22(a4)",
    "andi	a1, a1, 15",
    "sw	a3, 120(sp)", // 4-byte Folded Spill
    "sub	a0, a0, a3",
    "mul	a1, a2, a1",
    "sw	a1, 132(sp)", // 4-byte Folded Spill
    "slli	a0, a0, 16",
    "lui	a1, 4080",
    "mv	s1, a4",
    "jal	ra, 21b",
    "lb	a1, 24(s1)",
    "sw	a1, 116(sp)", // 4-byte Folded Spill
    "lbu	a1, 16(s1)",
    "sw	a1, 112(sp)", // 4-byte Folded Spill
    "lbu	a1, 18(s1)",
    "sw	a1, 108(sp)", // 4-byte Folded Spill
    "lbu	a1, 19(s1)",
    "sw	a1, 140(sp)", // 4-byte Folded Spill
    "lbu	a1, 23(s1)",
    "sw	a1, 104(sp)", // 4-byte Folded Spill
    "sw	a0, 100(sp)", // 4-byte Folded Spill
    "li	a0, 128",
    "lw	a1, 124(sp)", // 4-byte Folded Reload
    "jal	ra, 34b",
    "sw	a0, 96(sp)", // 4-byte Folded Spill
    "li	a0, 175",
    "lw	a1, 136(sp)", // 4-byte Folded Reload
    "bgeu	a0, a1, 89f",
    // in Loop: Header=BB16_1 Depth=1
    "lw	a0, 132(sp)", // 4-byte Folded Reload
    "neg	a0, a0",
    "sw	a0, 132(sp)", // 4-byte Folded Spill
    "89:", // .LBB16_18: in Loop: Header=BB16_1 Depth=1
    "lw	a1, 156(sp)", // 4-byte Folded Reload
    "sw	zero, 68(sp)", // 4-byte Folded Spill
    "sw	zero, 64(sp)", // 4-byte Folded Spill
    "sw	zero, 60(sp)", // 4-byte Folded Spill
    "li	t1, 0",
    "li	t2, 0",
    "li	a3, 0",
    "li	s1, 0",
    "lw	a0, 144(sp)", // 4-byte Folded Reload
    "sub	a0, a0, s0",
    "slli	a1, a1, 16",
    "sw	a1, 92(sp)", // 4-byte Folded Spill
    "lw	a1, 140(sp)", // 4-byte Folded Reload
    "slli	a1, a1, 8",
    "sw	a1, 88(sp)", // 4-byte Folded Spill
    "slli	a0, a0, 16",
    "srai	a1, a0, 31",
    "lw	a4, 128(sp)", // 4-byte Folded Reload
    "mulhu	a2, a0, a4",
    "mul	a1, a1, a4",
    "add	a1, a1, a2",
    "lw	a2, 48(sp)", // 4-byte Folded Reload
    "slli	a2, a2, 23",
    "mul	a0, a0, a4",
    "srli	a0, a0, 16",
    "slli	a1, a1, 16",
    "or	a0, a0, a1",
    "sw	a0, 84(sp)", // 4-byte Folded Spill
    "srli	a2, a2, 24",
    "sw	a2, 56(sp)", // 4-byte Folded Spill
    // implicit-def: $x10
    // kill: killed $x10
    "90:", // .LBB16_19: Parent Loop BB16_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB16_28 Depth 3
    "sw	a3, 136(sp)", // 4-byte Folded Spill
    "sw	t2, 140(sp)", // 4-byte Folded Spill
    "sw	t1, 144(sp)", // 4-byte Folded Spill
    "slli	a0, s1, 16",
    "lw	a1, 80(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "mv	s0, a0",
    // ERRATA BUG2 patch: lw	a0, 84(sp) (offset=84,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 88(sp)",
    "addi sp, sp, 4",
    "lw	a1, 92(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "li	a1, 128",
    "lw	a2, 108(sp)", // 4-byte Folded Reload
    "bltu	a1, a2, 91f",
    // in Loop: Header=BB16_19 Depth=2
    "neg	a0, a0",
    "91:", // .LBB16_21: in Loop: Header=BB16_19 Depth=2
    "lw	a1, 112(sp)", // 4-byte Folded Reload
    "mul	a1, a1, s0",
    "srai	a2, a1, 31",
    "lw	s0, 128(sp)", // 4-byte Folded Reload
    "mulhu	a3, a1, s0",
    "mul	a1, a1, s0",
    "mul	a2, a2, s0",
    "add	a2, a2, a3",
    "slli	a2, a2, 16",
    "srli	a1, a1, 16",
    "or	a1, a1, a2",
    "add	a0, a0, a1",
    "srai	a1, a0, 31",
    "xor	a0, a0, a1",
    "sub	ra, a0, a1",
    "bltu	ra, s0, 92f",
    // in Loop: Header=BB16_19 Depth=2
    "mv	a0, ra",
    "mv	a1, s0",
    "sw	ra, 72(sp)", // 4-byte Folded Spill
    "jal	ra, 21b",
    "lui	a1, 1048560",
    "and	a1, a1, a0",
    "srai	a0, a0, 31",
    "mul	a0, a0, s0",
    "mulhu	a2, a1, s0",
    "mul	a1, a1, s0",
    "add	a0, a0, a2",
    "slli	a0, a0, 16",
    "srli	a1, a1, 16",
    "or	a0, a0, a1",
    "lw	a1, 72(sp)", // 4-byte Folded Reload
    "sub	a0, a1, a0",
    "srai	a1, a0, 31",
    "and	a1, a1, s0",
    "add	ra, a0, a1",
    "92:", // .LBB16_23: in Loop: Header=BB16_19 Depth=2
    "li	t1, 16",
    "lw	a2, 132(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	a0, 148(sp) (offset=148,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 152(sp)",
    "addi sp, sp, 4",
    "bge	a0, ra, 93f",
    // in Loop: Header=BB16_19 Depth=2
    "sub	ra, s0, ra",
    "93:", // .LBB16_25: in Loop: Header=BB16_19 Depth=2
    "mv	s0, ra",
    "lw	a0, 160(sp)", // 4-byte Folded Reload
    "blt	ra, a0, 94f",
    // in Loop: Header=BB16_19 Depth=2
    // ERRATA BUG2 patch: lw	a0, 148(sp) (offset=148,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 152(sp)",
    "addi sp, sp, 4",
    "sub	s0, a0, ra",
    "94:", // .LBB16_27: in Loop: Header=BB16_19 Depth=2
    "li	a0, 0",
    "li	a3, 0",
    "lw	a1, 96(sp)", // 4-byte Folded Reload
    "mv	t2, s1",
    "mul	a1, a1, s1",
    "add	a1, a1, a2",
    "andi	a1, a1, 511",
    "sltiu	a2, a1, 256",
    "slli	a1, a1, 16",
    "addi	a2, a2, -1",
    "lui	a4, 8176",
    "and	a2, a2, a4",
    "xor	a1, a1, a2",
    "lw	a2, 100(sp)", // 4-byte Folded Reload
    "mulh	t0, a1, a2",
    "lui	a5, %hi(110f)",
    "addi	a5, a5, %lo(110f)",
    "lw	s1, 76(sp)", // 4-byte Folded Reload
    "95:", // .LBB16_28: Parent Loop BB16_1 Depth=1
    // Parent Loop BB16_19 Depth=2
    // =>    This Inner Loop Header: Depth=3
    "lw	a1, 0(a5)",
    "sra	a4, a0, a3",
    "sra	a2, s1, a3",
    "bltz	s0, 96f",
    // in Loop: Header=BB16_28 Depth=3
    "sub	s1, s1, a4",
    "add	a0, a0, a2",
    "sub	s0, s0, a1",
    "j	97f",
    "96:", // .LBB16_30: in Loop: Header=BB16_28 Depth=3
    "add	s1, s1, a4",
    "sub	a0, a0, a2",
    "add	s0, s0, a1",
    "97:", // .LBB16_31: in Loop: Header=BB16_28 Depth=3
    "addi	a3, a3, 1",
    "addi	a5, a5, 4",
    "bne	a3, t1, 95b",
    // in Loop: Header=BB16_19 Depth=2
    "lw	a0, 160(sp)", // 4-byte Folded Reload
    "blt	ra, a0, 98f",
    // in Loop: Header=BB16_19 Depth=2
    "neg	s1, s1",
    "98:", // .LBB16_34: in Loop: Header=BB16_19 Depth=2
    "lw	a3, 156(sp)", // 4-byte Folded Reload
    "slli	a0, s1, 7",
    "lui	a1, 2032",
    "sub	a1, s1, a1",
    "sub	a0, a0, a1",
    "srli	a1, a0, 16",
    // ERRATA BUG2 patch: lw	a0, 116(sp) (offset=116,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a0, 120(sp)",
    "addi sp, sp, 4",
    "bgez	a0, 99f",
    // in Loop: Header=BB16_19 Depth=2
    "andi	a0, a1, 255",
    "mul	a1, a0, a0",
    "srli	a1, a1, 8",
    "99:", // .LBB16_36: in Loop: Header=BB16_19 Depth=2
    "mv	s1, t2",
    "lw	a0, 120(sp)", // 4-byte Folded Reload
    "add	t0, t0, a0",
    "slli	a1, a1, 24",
    "andi	a0, t0, 255",
    "srli	a1, a1, 8",
    "lw	a2, 88(sp)", // 4-byte Folded Reload
    "or	a0, a0, a2",
    "lui	a2, 1044480",
    "and	a2, a2, a3",
    "or	a0, a0, a2",
    "or	a0, a0, a1",
    "sw	a0, 156(sp)", // 4-byte Folded Spill
    "jal	ra, 51b",
    "mv	s0, a0",
    "srli	a5, a0, 8",
    "li	a0, 87",
    "lw	a1, 104(sp)", // 4-byte Folded Reload
    "bltu	a0, a1, 100f",
    // in Loop: Header=BB16_19 Depth=2
    "lw	a0, 56(sp)", // 4-byte Folded Reload
    "lw	a1, 152(sp)", // 4-byte Folded Reload
    "sw	a5, 144(sp)", // 4-byte Folded Spill
    "jal	ra, 37b",
    "lw	a5, 144(sp)", // 4-byte Folded Reload
    "lw	a1, 124(sp)", // 4-byte Folded Reload
    "sltu	a1, a0, a1",
    "neg	a2, a1",
    "addi	a3, a1, -1",
    "andi	a1, a2, -64",
    "andi	a2, a3, -64",
    "sw	a2, 64(sp)", // 4-byte Folded Spill
    "sw	a2, 68(sp)", // 4-byte Folded Spill
    "sw	a2, 60(sp)", // 4-byte Folded Spill
    "mv	a2, a1",
    "mv	t0, a1",
    // ERRATA BUG2 patch: lw	a4, 52(sp) (offset=52,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a4, 56(sp)",
    "addi sp, sp, 4",
    "mv	t1, a1",
    "mv	t2, a1",
    "mv	a3, a1",
    "bne	a0, s1, 102f",
    "j	103f",
    "100:", // .LBB16_38: in Loop: Header=BB16_19 Depth=2
    "srli	a0, s0, 16",
    "mv	t0, s0",
    "mv	a2, a5",
    "mv	a1, a0",
    "beqz	s1, 101f",
    // in Loop: Header=BB16_19 Depth=2
    "lw	t0, 136(sp)", // 4-byte Folded Reload
    "lw	a2, 140(sp)", // 4-byte Folded Reload
    "lw	a1, 144(sp)", // 4-byte Folded Reload
    "101:", // .LBB16_40: in Loop: Header=BB16_19 Depth=2
    "lw	a4, 124(sp)", // 4-byte Folded Reload
    "bne	s1, a4, 102f",
    // in Loop: Header=BB16_19 Depth=2
    "sw	a0, 68(sp)", // 4-byte Folded Spill
    "sw	a5, 64(sp)", // 4-byte Folded Spill
    "sw	s0, 60(sp)", // 4-byte Folded Spill
    "102:", // .LBB16_42: in Loop: Header=BB16_19 Depth=2
    "andi	a0, a5, 224",
    "slli	a4, s0, 3",
    "slli	a0, a0, 11",
    "andi	a4, a4, 1792",
    "srli	s0, s0, 21",
    "or	a4, a4, s0",
    "or	a4, a4, a0",
    "mv	t1, a1",
    "mv	t2, a2",
    "mv	a3, t0",
    "103:", // .LBB16_43: in Loop: Header=BB16_19 Depth=2
    "slli	a0, s1, 2",
    "lui	a1, %hi(111f)",
    "addi	a1, a1, %lo(111f)",
    "add	a0, a0, a1",
    "addi	s1, s1, 1",
    "sw	a4, 36(a0)",
    "lw	a0, 152(sp)", // 4-byte Folded Reload
    "bne	s1, a0, 90b",
    // in Loop: Header=BB16_1 Depth=1
    "andi	a0, t2, 248",
    "slli	s1, a3, 5",
    "slli	a2, t1, 24",
    "lw	a1, 64(sp)", // 4-byte Folded Reload
    "andi	a3, a1, 248",
    "lw	a4, 60(sp)", // 4-byte Folded Reload
    "slli	a4, a4, 5",
    "lw	a5, 68(sp)", // 4-byte Folded Reload
    "slli	a5, a5, 24",
    "slli	a0, a0, 13",
    "lw	a1, 24(sp)", // 4-byte Folded Reload
    "and	s1, s1, a1",
    "srli	a2, a2, 27",
    "slli	a3, a3, 13",
    "and	a4, a4, a1",
    "srli	a5, a5, 27",
    "or	a0, a0, a2",
    "or	a3, a3, a5",
    "or	a0, a0, s1",
    "or	a1, a3, a4",
    "lw	s0, 44(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	s1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 24(sp)",
    "addi sp, sp, 4",
    "lui	a4, %hi(111f)",
    "addi	a4, a4, %lo(111f)",
    "j	106f",
    "104:", // .LBB16_45: in Loop: Header=BB16_1 Depth=1
    "lw	a0, 36(sp)", // 4-byte Folded Reload
    "jal	ra, 73b",
    "lui	a5, %hi(111f)",
    "li	a2, 35",
    "lui	a4, %hi(111f)",
    "addi	a4, a4, %lo(111f)",
    "lw	a1, 4(a4)",
    "j	107f",
    "105:", // .LBB16_46: in Loop: Header=BB16_1 Depth=1
    "li	a1, 0",
    "lw	s0, 44(sp)", // 4-byte Folded Reload
    "106:", // .LBB16_47: in Loop: Header=BB16_1 Depth=1
    "lui	a5, %hi(111f)",
    "lbu	a2, %lo(111f)(a5)",
    "addi	a3, a5, %lo(111f)",
    "neg	a2, a2",
    "and	a0, a0, a2",
    "and	a1, a1, a2",
    "sw	a0, 28(a3)",
    "sw	a1, 32(a3)",
    "li	a2, 35",
    "lw	a1, 48(sp)", // 4-byte Folded Reload
    "107:", // .LBB16_48: in Loop: Header=BB16_1 Depth=1
    "li	a0, 0",
    "addi	a1, a1, 1",
    "sw	a1, 4(a4)",
    "lui	a3, 196608",
    "108:", // .LBB16_49: Parent Loop BB16_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB16_50 Depth 3
    "mv	a1, s1",
    "109:", // .LBB16_50: Parent Loop BB16_1 Depth=1
    // Parent Loop BB16_49 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 109b",
    // in Loop: Header=BB16_49 Depth=2
    "lw	a1, 8(a4)",
    "addi	a1, a1, 1",
    "addi	a0, a0, 1",
    "sw	a1, 8(a4)",
    "bne	a0, a2, 108b",
    // in Loop: Header=BB16_1 Depth=1
    "addi	a0, s0, -1",
    "sltu	a1, s0, a0",
    "addi	a1, a1, -1",
    "and	s0, a1, a0",
    "j	80b",
    // --- rodata: cordic_atan_table (16 entries, 16 words) ---
    ".p2align 2",
    "110:", // cordic_atan_table
    ".word 0x0000c910", // [0] 51472
    ".word 0x000076b2", // [4] 30386
    ".word 0x00003eb7", // [8] 16055
    ".word 0x00001fd6", // [12] 8150
    ".word 0x00000ffb", // [16] 4091
    ".word 0x000007ff", // [20] 2047
    ".word 0x00000400", // [24] 1024
    ".word 0x00000200", // [28] 512
    ".word 0x00000100", // [32] 256
    ".word 0x00000080", // [36] 128
    ".word 0x00000040", // [40] 64
    ".word 0x00000020", // [44] 32
    ".word 0x00000010", // [48] 16
    ".word 0x00000008", // [52] 8
    ".word 0x00000004", // [56] 4
    ".word 0x00000002", // [60] 2
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "111:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: loop_state (4 entries, 1 words) ---
    ".p2align 0",
    "112:", // loop_state
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: time_ms (4 entries, 1 words) ---
    ".p2align 0",
    "113:", // time_ms
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: reftime_lg (4 entries, 1 words) ---
    ".p2align 0",
    "114:", // reftime_lg
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: diploid (12 entries, 3 words) ---
    ".p2align 0",
    "115:", // diploid
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    // --- rodata: led_buf (40 entries, 10 words) ---
    ".p2align 0",
    "116:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000" // [36] 0, 0, 0, 0
);
